// useRawData_RPC7247.js
import { useState } from "react";

export const rawData = [
  // Row 6 - AIRWORTHINES CERTIFICATE
  { _id: "6", rowType: "part", componentName: "AIRWORTHINES CERTIFICATE", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "365", dayType: "D", dateCW: "2026-03-31", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 7 - REGISTRATION CERTIFICATE
  { _id: "7", rowType: "part", componentName: "REGISTRATION CERTIFICATE", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "365", dayType: "D", dateCW: "2026-02-23", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 8 - RADIO LICENSE
  { _id: "8", rowType: "part", componentName: "RADIO LICENSE", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "1095", dayType: "D", dateCW: "2025-03-04", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 9 - WEIGHT & BALANCE
  { _id: "9", rowType: "part", componentName: "WEIGHT & BALANCE", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "1825", dayType: "D", dateCW: "2022-07-01", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 10 - FIRST AID KIT
  { _id: "10", rowType: "part", componentName: "FIRST AID KIT", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "365", dayType: "D", dateCW: "2025-06-20", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 11 - FIRE EXTINGUISHER
  { _id: "11", rowType: "part", componentName: "FIRE EXTINGUISHER PN: H1-10AIR SN: 1051061", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "3650", dayType: "D", dateCW: "2024-12-18", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 12 - TRANSPONDER CHECK
  { _id: "12", rowType: "part", componentName: "TRANSPONDER CHECK", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "365", dayType: "D", dateCW: "2026-03-17", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 13 - ELT check
  { _id: "13", rowType: "part", componentName: "ELT check", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "365", dayType: "D", dateCW: "2026-03-17", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 14 - ELT BATTERY
  { _id: "14", rowType: "part", componentName: "ELT BATTERY PN: S1820516-99", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "2190", dayType: "D", dateCW: "2024-12-18", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 15 - PITOT static check
  { _id: "15", rowType: "part", componentName: "PITOT static check", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "730", dayType: "D", dateCW: "2025-12-18", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 17 - 50 hrs SOAP analysis
  { _id: "17", rowType: "part", componentName: "50 hrs SOAP analysis", hourLimit1: "50", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "D", dateCW: "31/12/26", hoursCW: "3130", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 18 - NEXT 10 HRS. INSPECTION
  { _id: "18", rowType: "part", componentName: "NEXT 10 HRS. INSPECTION", hourLimit1: "10", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "D", dateCW: "2025-05-02", hoursCW: "3130", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 19 - NEXT 150 HRS. INSPECTION
  { _id: "19", rowType: "part", componentName: "NEXT 150 HRS. INSPECTION", hourLimit1: "150", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "D", dateCW: "2025-03-02", hoursCW: "3004.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 20 - 150 HRS / 12 M
  { _id: "20", rowType: "part", componentName: "150 HRS / 12 M", hourLimit1: "150", hourLimit2: "H", hourLimit3: "", dayLimit: "365", dayType: "D", dateCW: "2025-12-01", hoursCW: "2854.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 21 - 12M INSPECTION
  { _id: "21", rowType: "part", componentName: "12M INSPECTION", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "365", dayType: "D", dateCW: "2025-12-01", hoursCW: "2854.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 22 - HMU REPLACEMENT
  { _id: "22", rowType: "part", componentName: "HMU REPLACEMENT PN.0292862200 SR.50613", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "3650", dayType: "D", dateCW: "2017-04-10", hoursCW: "838.9", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 23 - 600HRS
  { _id: "23", rowType: "part", componentName: "600HRS", hourLimit1: "600", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2021-05-26", hoursCW: "2712.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 24 - 600HRS / 24M
  { _id: "24", rowType: "part", componentName: "600HRS / 24M", hourLimit1: "600", hourLimit2: "H", hourLimit3: "", dayLimit: "730", dayType: "D", dateCW: "2024-05-26", hoursCW: "2712.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 25 - 1200HRS
  { _id: "25", rowType: "part", componentName: "1200HRS", hourLimit1: "1200", hourLimit2: "H", hourLimit3: "", dayLimit: "1460", dayType: "", dateCW: "2024-05-26", hoursCW: "2712.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 26 - 1200HRS / 48M
  { _id: "26", rowType: "part", componentName: "1200HRS / 48M", hourLimit1: "1200", hourLimit2: "H", hourLimit3: "", dayLimit: "1460", dayType: "D", dateCW: "2024-07-05", hoursCW: "2405.7", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 27 - 5000HRS / 144M
  { _id: "27", rowType: "part", componentName: "5000HRS / 144M", hourLimit1: "5000", hourLimit2: "H", hourLimit3: "", dayLimit: "4380", dayType: "D", dateCW: "2024-09-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 28 - Engine Fuel Filter
  { _id: "28", rowType: "part", componentName: "Engine Fuel Filter P/N: 0292911940", hourLimit1: "600", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "D", dateCW: "2021-05-25", hoursCW: "2712.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 29 - Engine Oil Filter
  { _id: "29", rowType: "part", componentName: "Engine Oil Filter P/N:9560166860 PN:9560171250", hourLimit1: "800", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "D", dateCW: "2020-03-11", hoursCW: "2546.8", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 30 - MGB Oil Filter
  { _id: "30", rowType: "part", componentName: "MGB Oil Filter P/N: 7050A3632296 (POST-MOD 077162)", hourLimit1: "600", hourLimit2: "H", hourLimit3: "", dayLimit: "730", dayType: "D", dateCW: "2024-05-26", hoursCW: "2712.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "( Margin 73D)" },
  // Row 31 - Hydraulic Filter
  { _id: "31", rowType: "part", componentName: "Hydraulic Filter P/N: 806966", hourLimit1: "2500", hourLimit2: "H", hourLimit3: "", dayLimit: "1460", dayType: "D", dateCW: "2024-05-26", hoursCW: "2712.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 32 - HYDRAULIC FLUID CHANGE
  { _id: "32", rowType: "part", componentName: "HYDRAULIC FLUID CHANGE", hourLimit1: "", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "D", dateCW: "2025-03-31", hoursCW: "1305.7", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "( Margin 73D)" },
  // Row 33 - SLING
  { _id: "33", rowType: "part", componentName: "SLING", hourLimit1: "", hourLimit2: "H", hourLimit3: "", dayLimit: "365", dayType: "D", dateCW: "2025-02-16", hoursCW: "1229.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 34 - TRDS BEARING
  { _id: "34", rowType: "part", componentName: "TRDS BEARING PN:704A33651181 (60 MONTHS)", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "1825", dayType: "D", dateCW: "2025-05-21", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 35 - HYD PUMP Drive Brg.
  { _id: "35", rowType: "part", componentName: "HYD PUMP Drive Brg. P/N: 704A33651269 (72 MONTHS)", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "2190", dayType: "D", dateCW: "2025-05-26", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 36 - ENGINE BORESCOPE INSP.
  { _id: "36", rowType: "part", componentName: "ENGINE BORESCOPE INSP.", hourLimit1: "800", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "D", dateCW: "2025-05-26", hoursCW: "2712.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 38 - AIRFRAME COMPONENT (Header)
  { _id: "38", rowType: "header", componentName: "AIRFRAME COMPONENT", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 39 - Electrical Power System (Header)
  { _id: "39", rowType: "header", componentName: "Electrical Power System", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 40 - Saft Battery
  { _id: "40", rowType: "part", componentName: "Saft Battery (Ni-Cad)PN:151CH1 SN: X02470", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "OC", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 41 - Saft Battery Top Charge
  { _id: "41", rowType: "part", componentName: "Saft Battery (Ni-Cad)PN:151CH1 SN: X02470 Top Charge", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "91", dayType: "D", dateCW: "2026-04-10", hoursCW: "3130", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 42 - Fire Protection (Header)
  { _id: "42", rowType: "header", componentName: "Fire Protection", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 43 - Cabin Fire Extinguisher
  { _id: "43", rowType: "part", componentName: "Cabin Fire Extinguisher  PN:H1-10-AIR SN:1051061", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "3650", dayType: "D", dateCW: "2025-08-18", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 44 - Cabin Fire Extinguisher Re-weigh
  { _id: "44", rowType: "part", componentName: "Cabin Fire Extinguisher  Re-weigh", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "365", dayType: "", dateCW: "2027-03-10", hoursCW: "3130", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 45 - Floats of Emergency Flotation System (Header)
  { _id: "45", rowType: "header", componentName: "Floats of Emergency Flotation System", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 46 - Emergency Floats R/H
  { _id: "46", rowType: "part", componentName: "Emergency (Floats R/H) PN:200734-0 SN:3673", hourLimit1: "", hourLimit2: "RH", hourLimit3: "", dayLimit: "4380", dayType: "D", dateCW: "2024-07-03", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 47 - Emergency Floats L/H
  { _id: "47", rowType: "part", componentName: "Emergency (Floats L/H) PN:200733-0 SN:3668", hourLimit1: "", hourLimit2: "LH", hourLimit3: "", dayLimit: "4380", dayType: "D", dateCW: "2024-07-03", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 48 - Emergency Floats Gear Cylinder RH
  { _id: "48", rowType: "part", componentName: "Emergency Floats Gear(Cylinder ASSY) PN: 200740-2 SN:7042", hourLimit1: "", hourLimit2: "RH", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2020-07-27", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 49 - Emergency Floats Gear Cylinder LH
  { _id: "49", rowType: "part", componentName: "Emergency Floats Gear(Cylinder ASSY) PN:200740-2 SN:7024", hourLimit1: "", hourLimit2: "LH", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2020-07-27", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 50 - Hydrotest Floats Gear Cylinder SN#2116
  { _id: "50", rowType: "part", componentName: "Hydrotest Floats Gear Cylinder  PN: 200740-2 SN#2116", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "1825", dayType: "D", dateCW: "2024-02-16", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 51 - Hydrotest Floats Gear Cylinder SN#2381
  { _id: "51", rowType: "part", componentName: "Hydrotest Floats Gear Cylinder  PN: 200740-2 SN#2381", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "1825", dayType: "D", dateCW: "2024-02-16", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 52 - Onboard Systems TSI 60M
  { _id: "52", rowType: "part", componentName: "Onboard  Systems  PN: 52802351  SN#3403 TSI 60M", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "1825", dayType: "D", dateCW: "2024-02-16", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 53 - Onboard Systems
  { _id: "53", rowType: "part", componentName: "Onboard  Systems  PN: 52802351  SN#3403", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "3650", dayType: "D", dateCW: "2024-03-01", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 54 - Main Rotor Blade (Header)
  { _id: "54", rowType: "header", componentName: "Main Rotor Blade", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 55 - Main Rotor Blade RED
  { _id: "55", rowType: "part", componentName: "Main Rotor Blade PN:355A11-0030.04 SN:40055 RED", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2025-01-03", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 56 - Main Rotor Blade BLUE
  { _id: "56", rowType: "part", componentName: "Main Rotor Blade PN:355A11-0030.04 SN:40056 BLUE", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2025-01-03", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 57 - Main Rotor Blade YELLOW
  { _id: "57", rowType: "part", componentName: "Main Rotor Blade PN:355A11-0030.04 SN:40060 YELLOW", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2025-01-03", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 58 - Poly-Urethane Tape (MRB) (Header)
  { _id: "58", rowType: "header", componentName: "Poly-Urethane Tape (MRB)", hourLimit1: "OC", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 59 - Main Rotor Head (Header)
  { _id: "59", rowType: "header", componentName: "Main Rotor Head", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 60-65 - Unequipped Blade Pin (6 rows)
  { _id: "60", rowType: "part", componentName: "Unequipped Blade Pin PN:350A31-1771-21 SN:M38434", hourLimit1: "INF", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "61", rowType: "part", componentName: "Unequipped Blade Pin PN:350A31-1771-21 SN:M38435", hourLimit1: "INF", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "62", rowType: "part", componentName: "Unequipped Blade Pin PN:350A31-1771-21 SN:M38439", hourLimit1: "INF", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "63", rowType: "part", componentName: "Unequipped Blade Pin PN:350A31-1771-21 SN:M38440", hourLimit1: "INF", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "64", rowType: "part", componentName: "Unequipped Blade Pin PN:350A31-1771-21 SN:M38441", hourLimit1: "INF", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "65", rowType: "part", componentName: "Unequipped Blade Pin PN:350A31-1771-21 SN:M38445", hourLimit1: "INF", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 66-68 - Sleeve Flange Lower (3 rows)
  { _id: "66", rowType: "part", componentName: "Sleeve Flange ,Lower PN:350A31-1850-02 SN:M27792", hourLimit1: "4400", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "67", rowType: "part", componentName: "Sleeve Lower Flange PN:350A31-1850-02 SN:M27795", hourLimit1: "4400", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "68", rowType: "part", componentName: "Sleeve Lower Flange PN:350A31-1850-02 SN:M27798", hourLimit1: "4400", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 69-71 - Sleeve Upper Flange (3 rows)
  { _id: "69", rowType: "part", componentName: "Sleeve Upper Flange PN:350A31185003 SN:M27753", hourLimit1: "4400", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "70", rowType: "part", componentName: "Sleeve Upper Flange PN:350A31185003 SN:M27754", hourLimit1: "4400", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "71", rowType: "part", componentName: "Sleeve Upper Flange PN:350A31185003 SN:M27755", hourLimit1: "4400", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 72-78 - Spherical Thrust Bearing Bolt (7 rows)
  { _id: "72", rowType: "part", componentName: "Spherical Thrust Bearing Bolt PN:350A31185421 SN:85545", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-03-01", hoursCW: "3000", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "73", rowType: "part", componentName: "Spherical Thrust Bearing Bolt PN:350A31185421 SN:72086", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2021-03-01", hoursCW: "2711.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "74", rowType: "part", componentName: "Spherical Thrust Bearing Bolt PN:350A31185421 SN:70742", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2017-03-01", hoursCW: "1678.9", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "622" },
  { _id: "75", rowType: "part", componentName: "Spherical Thrust Bearing Bolt PN:350A31185421 SN:85546", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "76", rowType: "part", componentName: "Spherical Thrust Bearing Bolt PN:350A31185421 SN:62007", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2017-03-01", hoursCW: "1678.9", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "77", rowType: "part", componentName: "Spherical Thrust Bearing Bolt PN:350A31185421 SN:88564", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 78-80 - Blade Horn (3 rows)
  { _id: "78", rowType: "part", componentName: "Blade Horn PN:350A31187703 SN:MAP7245", hourLimit1: "80000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "79", rowType: "part", componentName: "Blade Horn PN:350A31187703 SN:MAP7339", hourLimit1: "80000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "80", rowType: "part", componentName: "Blade Horn PN:350A31187703 SN:MAP7344", hourLimit1: "80000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 81 - Star Flex Rotor Hub
  { _id: "81", rowType: "part", componentName: "Star Flex Rotor Hub PN:350A31-1918-00 SR:M1066", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2013-08-01", hoursCW: "398.4", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 82-84 - Spherical Thrust Bearing (3 rows)
  { _id: "82", rowType: "part", componentName: "Spherical Thrust Bearing PN:704A33633211 SN:20725", hourLimit1: "6400", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "83", rowType: "part", componentName: "Spherical Thrust Bearing PN:704A33633211 SN:20726", hourLimit1: "6400", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "84", rowType: "part", componentName: "Spherical Thrust Bearing PN:704A33633211 SN:20727", hourLimit1: "6400", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 85 - Main Rotor (Header)
  { _id: "85", rowType: "header", componentName: "Main Rotor", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 86 - MAIN ROTOR PN (Header)
  { _id: "86", rowType: "header", componentName: "MAIN ROTOR PN:350A37004-02 SN:M2860", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 87 - Main Rotor Shaft
  { _id: "87", rowType: "part", componentName: "Main Rotor Shaft PN:350A-37-1290-04 SN:M6416", hourLimit1: "90000", hourLimit2: "TC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 88-99 - MRH Attachment Bolt (12 rows)
  { _id: "88", rowType: "part", componentName: "MRH Attachment Bolt PN:350A37124420 SN:128982", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "89", rowType: "part", componentName: "MRH Attachment Bolt PN:350A37124420 SN:129243", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "90", rowType: "part", componentName: "MRH Attachment Bolt PN:350A37124420 SN:129254", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "91", rowType: "part", componentName: "MRH Attachment Bolt PN:350A37124420 SN:130996", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "92", rowType: "part", componentName: "MRH Attachment Bolt PN:350A37124420 SN:131075", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "93", rowType: "part", componentName: "MRH Attachment Bolt PN:350A37124420 SN96098", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "94", rowType: "part", componentName: "MRH Attachment Bolt PN:350A37124520 SN:112662", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "95", rowType: "part", componentName: "MRH Attachment Bolt PN:350A37124520 SN:112754", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "96", rowType: "part", componentName: "MRH Attachment Bolt PN:350A37124520 SN:112781", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "97", rowType: "part", componentName: "MRH Attachment Bolt PN:350A37124520 SN:113344", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "98", rowType: "part", componentName: "MRH Attachment Bolt PN:350A37124420 SN:113482", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "99", rowType: "part", componentName: "MRH Attachment Bolt PN:350A37124420 SN:113396", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 100 - Swashplate Bearing
  { _id: "100", rowType: "part", componentName: "Swashplate Bearing PN:704A33651158 SN:NR9292", hourLimit1: "4800", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 101 - Main Gear Box TBO (Header)
  { _id: "101", rowType: "header", componentName: "Main Gear Box TBO", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 102 - FUEL PUMP (Header)
  { _id: "102", rowType: "header", componentName: "FUEL PUMP", hourLimit1: "", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 103 - TRANSMISSION OIL CHANGE (Header)
  { _id: "103", rowType: "header", componentName: "TRANSMISSION OIL CHANGE", hourLimit1: "", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 104 - Epicyclic Reduction Gear
  { _id: "104", rowType: "part", componentName: "Epicyclic Reduction Gear PN:350A32-0120-00 SN:M9265", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2025-08-23", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 105 - Conic Pinion
  { _id: "105", rowType: "part", componentName: "Conic Pinion  PN:350A32-3173-20 SN:L4756", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 106 - Bevel Wheel
  { _id: "106", rowType: "part", componentName: "Bevel Wheel PN:350A32-3166-20 SN:L3012", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 107 - Sump Casing
  { _id: "107", rowType: "part", componentName: "Sump Casing PN:350A32-3119-05 SN:MAP8378", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 108 - Planet Gear Assy L30965
  { _id: "108", rowType: "part", componentName: "Planet Gear Assy PN:350A32-1082-03 SN:L30965", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 109-112 - additional Planet Gear Assy
  { _id: "109", rowType: "part", componentName: "Planet Gear Assy PN:350A32-1082-03 SN:L33250", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "110", rowType: "part", componentName: "Planet Gear Assy PN:350A32-1082-03 SN:L33303", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "111", rowType: "part", componentName: "Planet Gear Assy PN:350A32-1082-03 SN:L34104", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "112", rowType: "part", componentName: "Planet Gear Assy PN:350A32-1082-03 SN:L34201", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 113 - Planet Gear Holder
  { _id: "113", rowType: "part", componentName: "Planet Gear Holder PN:350A32-1089-21 SN:CUR01953", hourLimit1: "49000", hourLimit2: "TC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 114 - Pump Assy. Oil
  { _id: "114", rowType: "part", componentName: "Pump Assy. Oil PN:350A32-0400-00 SN:M4910", hourLimit1: "3500", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-05-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 115 - Tail Rotor Blades (Header)
  { _id: "115", rowType: "header", componentName: "Tail Rotor Blades", hourLimit1: "", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 116 - Tail Rotor Blade
  { _id: "116", rowType: "part", componentName: "Tail Rotor Blade PN:355A12-0060-02 SN:24013", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-04", hoursCW: "1224", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "140.5", totalTimeSinceNew: "" },
  // Row 117 - Poly-Urethane Tapes (Header)
  { _id: "117", rowType: "header", componentName: "Poly-Urethane Tapes", hourLimit1: "OC", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 118 - HANGER BEARING (Header)
  { _id: "118", rowType: "header", componentName: "HANGER BEARING", hourLimit1: "", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 119 - SPLIT BUSHING (Header)
  { _id: "119", rowType: "header", componentName: "SPLIT BUSHING PN:350A37-1294-21", hourLimit1: "", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 120 - TAIL GEARBOX OIL CHANGE (Header)
  { _id: "120", rowType: "header", componentName: "TAIL GEARBOX OIL CHANGE", hourLimit1: "", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 121 - Tail Rotor Gear Box (Header)
  { _id: "121", rowType: "header", componentName: "Tail Rotor Gear Box", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 122 - Tail Rotor Gear Box PN
  { _id: "122", rowType: "part", componentName: "Tail Rotor Gear Box PN: 350A33-0210-00 SN:MA90884", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-08-25", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 123 - Pitch Change Unit
  { _id: "123", rowType: "part", componentName: "Pitch Change Unit PN: 350A33-1535-00 SN: MA69182", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-07-20", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 124 - Bevel Wheel
  { _id: "124", rowType: "part", componentName: "Bevel Wheel PN:350A33-1001-21 SN:L12917", hourLimit1: "5500", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-07-20", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 125 - Bevel Gear
  { _id: "125", rowType: "part", componentName: "Bevel Gear  PN:350A33-1000-21 SN:L14737", hourLimit1: "5500", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-07-20", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 126 - Casing
  { _id: "126", rowType: "part", componentName: "Casing PN:350A33-1090-02 SN:MA86501", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-07-20", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 127 - Tail Rotor Drive Shaft
  { _id: "127", rowType: "part", componentName: "Tail Rotor Drive Shaft PN:350A33-1092-01 SN:MA85444", hourLimit1: "20000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-07-20", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 128 - Spider bearing (first)
  { _id: "128", rowType: "part", componentName: "Spider bearing. PN: 350A33216701 SN:MA3459", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-07", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 129 - Spider bearing (second)
  { _id: "129", rowType: "part", componentName: "Spider bearing. PN: 350A33216701 SN:MA3459", hourLimit1: "3000", hourLimit2: "", hourLimit3: "", dayLimit: "1825", dayType: "D", dateCW: "2011-06-07", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 130 - Hanger bearing (hour)
  { _id: "130", rowType: "part", componentName: "Hanger bearing.", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2024-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 131 - Hanger bearing (day)
  { _id: "131", rowType: "part", componentName: "Hangerr bearing.", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "1825", dayType: "D", dateCW: "2024-06-01", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 132 - Pitch Rod LK6157
  { _id: "132", rowType: "part", componentName: "Pitch Rod PN:704A47137036 SN:LK6157", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "1825", dayType: "D", dateCW: "2024-06-01", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 133 - Pitch Rod LK6220
  { _id: "133", rowType: "part", componentName: "Pitch Rod PN:704A47137036 SN:LK6220", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "1825", dayType: "D", dateCW: "2024-06-01", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 134 - Servo Controls (Header)
  { _id: "134", rowType: "header", componentName: "Servo Controls", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 135 - MR Servo Control 3088
  { _id: "135", rowType: "part", componentName: "MR Servo Control PN:SC5083-1 SN:3088", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "7300", dayType: "D", dateCW: "2023-05-26", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 136 - MR Servo Control 4297
  { _id: "136", rowType: "part", componentName: "MR Servo Control  PN:SC5083-1 SN:4297", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "7300", dayType: "D", dateCW: "2023-08-25", hoursCW: "1713", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "1346", totalTimeSinceNew: "" },
  // Row 137 - MR Servo Control 2286
  { _id: "137", rowType: "part", componentName: "MR Servo Control  PN:SC5084-1 SN:2286", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "7300", dayType: "D", dateCW: "2023-08-25", hoursCW: "2028.9", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "1806.4", totalTimeSinceNew: "" },
  // Row 138 - TR Rear Servo Control
  { _id: "138", rowType: "part", componentName: "(TR) Rear Servo Control  PN:SC5072 SN:2626", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "7300", dayType: "D", dateCW: "2024-07-06", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 139 - Suspension Bars Forward
  { _id: "139", rowType: "part", componentName: "Suspension Bars , Forward PN: B211000-074 SN: 3496", hourLimit1: "3600", hourLimit2: "", hourLimit3: "", dayLimit: "2190", dayType: "", dateCW: "2024-07-06", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 140 - Starting (Header)
  { _id: "140", rowType: "header", componentName: "Starting", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 141 - Starter Generator
  { _id: "141", rowType: "part", componentName: "Starter Generator PN:704A46-1010-27 SN:S013998 MPN:150SG122Q-4", hourLimit1: "1200", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-01-01", hoursCW: "2412.2", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 142 - Checking of brushes 300h
  { _id: "142", rowType: "part", componentName: "Cheking of brushes 300h", hourLimit1: "3000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2023-01-01", hoursCW: "2712.6", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 143 - Hydraulic Pump Drive Brg.
  { _id: "143", rowType: "part", componentName: "Hydraulic Pump Drive Brg. P/N:350A35013201 SN:SAR166", hourLimit1: "3600", hourLimit2: "H", hourLimit3: "", dayLimit: "2190", dayType: "D", dateCW: "2024-09-30", hoursCW: "843.9", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 144 - Poly V Belt
  { _id: "144", rowType: "part", componentName: "Poly V Belt P/N: POLY-V597K4", hourLimit1: "3600", hourLimit2: "H", hourLimit3: "", dayLimit: "2190", dayType: "D", dateCW: "2024-04-17", hoursCW: "1678.9", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 145 - POWERPLANT COMPONENT/ ENGINE (Header)
  { _id: "145", rowType: "header", componentName: "POWERPLANT COMPONENT/ ENGINE", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 146 - Engine Model (Header)
  { _id: "146", rowType: "header", componentName: "Engine Model: Arriel 2D", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 147 - Date of Manufactured (Header)
  { _id: "147", rowType: "header", componentName: "Date of Manufactured: 2011-05-30", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 148 - ENGINE OIL CHANGE (Header)
  { _id: "148", rowType: "header", componentName: "ENGINE OIL CHANGE", hourLimit1: "", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "D", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 149 - Powerplant
  { _id: "149", rowType: "part", componentName: "Powerplant (Turbomeca Arriel 2D) SN:50307", hourLimit1: "5000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2018-09-11", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 150 - Module 01
  { _id: "150", rowType: "part", componentName: "Module 01- Accessory Gear Box  PN:70BM010020  SN:19309", hourLimit1: "5000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2018-09-11", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 151 - Module 02
  { _id: "151", rowType: "part", componentName: "Module 02- Axial Compressor PN:70BM020010  SN:20324", hourLimit1: "5000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2018-09-11", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 152 - Module 03
  { _id: "152", rowType: "part", componentName: "Module 03- Gas Generator PN:70BM030070  SN:26311", hourLimit1: "5000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2018-09-11", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 153 - Module 04
  { _id: "153", rowType: "part", componentName: "Module 04- Free Turbine PN:70BM040020  SN:24325", hourLimit1: "5000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2018-09-11", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 154 - Module 05
  { _id: "154", rowType: "part", componentName: "Module 05- Reduction Gear PN:70BM050010  SN:22324", hourLimit1: "5000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2018-09-11", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 155 - Module 02 TBO 4000Hrs (Header)
  { _id: "155", rowType: "header", componentName: "Module 02 TBO 4000Hrs", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 156 - Axial Compressor Wheel
  { _id: "156", rowType: "header", componentName: "Axial Compressor Wheel PN:2292153370 SN:1757FB", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 157 - N1 line
  { _id: "157", rowType: "header", componentName: "N1 22000 C LIFE LIMIT", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 158 - Axial comp. Front Bearing
  { _id: "158", rowType: "part", componentName: "Axial comp. Front Bearing PN:9609000486 SN:10035", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 159 - Axial comp. Rear Bearing
  { _id: "159", rowType: "part", componentName: "Axial comp. Rear Bearing PN:9609000486 SN:10036", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 160 - Bearing Bevelgear
  { _id: "160", rowType: "part", componentName: "Bearing Bevelgear PN:9609000727 SN:429", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 161 - Module 03 TBO-3500HRS
  { _id: "161", rowType: "header", componentName: "Module 03 TBO-3500HRS.", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 162 - Life Limited Parts (Header)
  { _id: "162", rowType: "header", componentName: "Life Limited Parts", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 163 - Centrifugal Impeller
  { _id: "163", rowType: "part", componentName: "Centrifugal  Impeller PN:0292260110 SN:2953CAR", hourLimit1: "22000", hourLimit2: "C", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 164 - Injection Wheel
  { _id: "164", rowType: "part", componentName: "Injection Wheel PN:2292260750 SN:9695AD", hourLimit1: "6500", hourLimit2: "C", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 165 - HP Turbine Disc
  { _id: "165", rowType: "part", componentName: "HP Turbine Disc PN:2292260060 SN:T581AD", hourLimit1: "17000", hourLimit2: "C", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 166 - Usage Limited Parts (Header)
  { _id: "166", rowType: "header", componentName: "Usage Limited Parts", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 167 - Bearing
  { _id: "167", rowType: "part", componentName: "Bearing PN:9609000493 SN:5498", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 168 - HP Turbine Blades
  { _id: "168", rowType: "part", componentName: "HP Turbine Blades PN:229226A2M0 SN:9619", hourLimit1: "10000", hourLimit2: "C", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 169 - Module 04 TBO-3500HRS
  { _id: "169", rowType: "header", componentName: "Module 04  TBO-3500HRS.", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 170 - Life Limited Parts (Header)
  { _id: "170", rowType: "header", componentName: "Life Limited Parts", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 171 - Free Turbine Disc
  { _id: "171", rowType: "part", componentName: "Free Turbine Disc PN: 2292810790 SN:2893TY", hourLimit1: "22000", hourLimit2: "C", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 172 - Usage Limited Parts (Header)
  { _id: "172", rowType: "header", componentName: "Usage Limited Parts", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 173 - Free Turbine Nut
  { _id: "173", rowType: "part", componentName: "Free Turbine Nut PN: 0292810450  SN:7742EPS", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 174 - Free Turbine Rear bearing (first)
  { _id: "174", rowType: "part", componentName: "Free Turbine Rear bearing PN: 9609000554 SN:5413", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 175 - Free Turbine Rear bearing (second)
  { _id: "175", rowType: "part", componentName: "Free Turbine Rear bearing PN: 9609000166 SN:24713", hourLimit1: "3500", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 176 - Free Turbine Blades (hour)
  { _id: "176", rowType: "part", componentName: "Free Turbine Blades PN:229281A440  SN:12678", hourLimit1: "6000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 177 - Free Turbine Blades (cycle)
  { _id: "177", rowType: "part", componentName: "Free Turbine Blades PN:229281A440  SN:12678", hourLimit1: "10000", hourLimit2: "C", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 178 - Module 05 TBO-3500HRS
  { _id: "178", rowType: "header", componentName: "Module 05  TBO-3500HRS.", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "3500", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 179 - Sleeve Assy
  { _id: "179", rowType: "part", componentName: "Sleeve Assy PN: 0292717600 SN:5441723HSP", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 180 - Nut
  { _id: "180", rowType: "part", componentName: "Nut PN: 0292710510 SN:8497EPS", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 181-190 - multiple bearings (9 rows)
  { _id: "181", rowType: "part", componentName: "Bearing PN: 9609000631 SN:4930", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "182", rowType: "part", componentName: "Bearing PN: 9609000489 SN:5857", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "183", rowType: "part", componentName: "Bearing PN: 9609000514 SN:5296", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "184", rowType: "part", componentName: "Bearing PN: 9609000676 SN:7262", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "185", rowType: "part", componentName: "Bearing PN: 9609000676 SN:7271", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "186", rowType: "part", componentName: "Bearing PN: 9609000675 SN:3317", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "187", rowType: "part", componentName: "Bearing PN: 9609000675 SN:3343", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "5475", dayType: "D", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 188 - Free Wheel Shaft Assy
  { _id: "188", rowType: "part", componentName: "Free Wheel Shaft Assy. PN: 0292900200 SN: 6014", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 189 - Free Wheel
  { _id: "189", rowType: "part", componentName: "Free Wheel PN: 9560901230 SN: 46", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 190 - Bearing
  { _id: "190", rowType: "part", componentName: "Bearing PN: 9606651001 SN: 24SN", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 191 - Bearing
  { _id: "191", rowType: "part", componentName: "Bearing PN: 9606681001 SN: 27SN", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 192 - Bearing
  { _id: "192", rowType: "part", componentName: "Bearing PN: 9606490606 SN: 24SN", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 193 - Free Wheel Flange
  { _id: "193", rowType: "part", componentName: "Free Wheel Flange  PN: 0292900250 SN: 23CZ", hourLimit1: "90000", hourLimit2: "C", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 194 - Free Wheel Shaft
  { _id: "194", rowType: "part", componentName: "Free Wheel Shaft  PN: 02929000230 SN: 57", hourLimit1: "120000", hourLimit2: "C", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-06-01", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 195 - Pump& Metering Valve (removed, skip)
  { _id: "195", rowType: "part", componentName: "Pump& Metering Valve Assy,AdjustedPN: 0292861650 SN:OFF 50034 SN:ON 50374", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "3650", dayType: "", dateCW: "", hoursCW: "", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "REMOVED DUE TO FUEL LEAK UPON COMPLIANCE OF SB" },
  // Row 196 - Pump& Metering Valve (installed)
  { _id: "196", rowType: "part", componentName: "Pump& Metering Valve Assy,AdjustedPN: 0292862200 SN:OFF 50451 SN:ON 50374", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "3650", dayType: "", dateCW: "2016-03-28", hoursCW: "1299.5", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 197 - Valve Assy
  { _id: "197", rowType: "part", componentName: "Valve AssyPN: 0292950250 SN:137", hourLimit1: "4000", hourLimit2: "H", hourLimit3: "", dayLimit: "3650", dayType: "", dateCW: "2019-07-31", hoursCW: "398.4", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 198 - CARGO SLING INSPECTION
  { _id: "198", rowType: "part", componentName: "CARGO SLING INSPECTION", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "365", dayType: "D", dateCW: "2024-06-10", hoursCW: "2594.7", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Row 199 - EQUIPMENTS/ACCESSORIES (Header)
  { _id: "199", rowType: "header", componentName: "EQUIPMENTS/ACCESSORIES", hourLimit1: "", hourLimit2: "", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2019-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  // Equipment items (OC)
  { _id: "200", rowType: "part", componentName: "EECU PN:70BMN01030 SN:1215", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2014-07-03", hoursCW: "624.5", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "201", rowType: "part", componentName: "H. E. Igniter PN:9550168770 SN:11022433", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "202", rowType: "part", componentName: "H. E. Igniter PN:9550168770 SN:11022450", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "203", rowType: "part", componentName: "Alternator PN:9550002100 SN:766", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "204", rowType: "part", componentName: "H.E Box PN: 9550178070 SN:7204", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "205", rowType: "part", componentName: "Torquemeter Sensor PN:9550175810 SN:12747", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "206", rowType: "part", componentName: "N1Speed Sensor PN:9550175810 SN:12384", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "207", rowType: "part", componentName: "N2 Speed Sensor PN:9550175800 SN:7717", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "208", rowType: "part", componentName: "N2 Speed Sensor PN:9550175800 SN:7723", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "209", rowType: "part", componentName: "N2 Speed Sensor PN:9550175800 SN:7767", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "210", rowType: "part", componentName: "Valve Assy  PN:0292727300 SN:7322", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "211", rowType: "part", componentName: "EDR PN:9580118050 SN:114", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "212", rowType: "part", componentName: "Control & Monitoring Harness PN:0292697770 SN:ON 413", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "213", rowType: "part", componentName: "Control harness PN:0292697830 SN:153EL", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "214", rowType: "part", componentName: "Thermocouple Indicating Harness PN:9550178220 SN:6419", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "215", rowType: "part", componentName: "Thermocouple Indicating Harness PN:9550178230 SN:5973", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "216", rowType: "part", componentName: "Fuel fiter vissual blockage indicator PN:9560166910 SN:7932", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "217", rowType: "part", componentName: "Injector PN:0283317500 SN: 15091MM", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "218", rowType: "part", componentName: "Injector PN:0283317500 SN: 15132MM", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "219", rowType: "part", componentName: "Oil Pressure Transmitter PN:9421000800 SN:TMAD000600", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "220", rowType: "part", componentName: "Oil Pressure and temp. Transmitter PN:9421001000 SN:TMAE000458", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "221", rowType: "part", componentName: "Oil Pump PN:0292125140 SN:2736MTL", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "222", rowType: "part", componentName: "P.3 Transmitter PN:9550171420 SN:BAY3344", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "223", rowType: "part", componentName: "Exhaust Duct PN:0292810470 SN:29EX", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "224", rowType: "part", componentName: "Fuel press. transmitter PN:9421000800 SN:TMAD000614", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "225", rowType: "part", componentName: "Fuel press. And temp. transmitter PN:9421001000 SN:TMAE000464", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "226", rowType: "part", componentName: "Bleed Valve PN:9550178980 SN: 804", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "227", rowType: "part", componentName: "Magnetic Plug PN:9560171170 SN:15060", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "228", rowType: "part", componentName: "Magnetic Plug PN:9560171170 SN:15066", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" },
  { _id: "229", rowType: "part", componentName: "Electrical Magnetic Plug PN:9550171750 SN:DV3180", hourLimit1: "", hourLimit2: "OC", hourLimit3: "", dayLimit: "", dayType: "", dateCW: "2011-07-15", hoursCW: "0", daysRemaining: "", timeRemaining: "", dateDue: "", ttCycleDue: "", due: "", hd: "", timeSinceInstall: "", totalTimeSinceNew: "" }
];

export const useRawData = () => {
  const [data, setData] = useState(rawData) // reference the exported array
  return { rawData: data, setRawData: setData };
};
