export const flightLogsMockData = [
  {
    id: "1",
    rpc: "7247",
    aircraftType: "AS350B3E",
    date: "02/24/2026",
    control: "Control value here",
    status: "pending_release",
    createdBy: "pilot",
    dateAdded: "02/24/2026",
    legs: [
      {
        stations: [{ from: "Manila", to: "Cebu" }],
        blockTimeOn: "08:00",
        blockTimeOff: "09:30",
        flightTimeOn: "08:15",
        flightTimeOff: "09:15",
        totalTimeOn: "1:00",
        totalTimeOff: "1:00",
        date: "02/24/2026",
        passengers: "12",
      },
    ],
    remarks: "Minor vibration noticed during climb",
    sling: "",
    fuelServicing: [
      {
        date: "02/24/2026",
        contCheck: "OK",
        mainRemG: "150",
        mainAdd: "50",
        mainTotal: "200",
        fuelType: "drum",
        refuelerName: "",
        signature: "",
      },
    ],
    oilServicing: [
      {
        date: "02/24/2026",
        engineRem: "8",
        engineAdd: "2",
        engineTot: "10",
        mrGboxRem: "5",
        mrGboxAdd: "1",
        mrGboxTot: "6",
        trGboxRem: "3",
        trGboxAdd: "0",
        trGboxTot: "3",
        remarks: "",
        signature: "",
      },
    ],
    componentData: {
      broughtForwardData: {
        airframe: "1250",
        gearBoxMain: "850",
        gearBoxTail: "425",
        rotorMain: "620",
        rotorTail: "310",
        airframeNextInsp: "1500",
        engine: "450",
        cycleN1: "320",
        cycleN2: "320",
        usage: "45",
        landingCycle: "280",
        engineNextInsp: "500",
      },
      thisFlightData: {},
      toDateData: {},
    },
    workItems: [],
    broughtForwardLocked: false,
    notifiedForCompletion: false,
    releasedBy: { name: "", signature: "", timestamp: "" },
    acceptedBy: { name: "", signature: "", timestamp: "" },
  },
  {
    id: "2",
    rpc: "7248",
    aircraftType: "AS350B3E",
    date: "02/23/2026",
    control: "Control value here",
    status: "pending_acceptance",
    createdBy: "engineer",
    dateAdded: "02/23/2026",
    legs: [],
    remarks: "",
    sling: "",
    fuelServicing: [
      {
        date: "02/23/2026",
        contCheck: "OK",
        mainRemG: "180",
        mainAdd: "20",
        mainTotal: "200",
        fuelType: "truck",
        refuelerName: "",
        signature: "",
      },
    ],
    oilServicing: [
      {
        date: "02/23/2026",
        engineRem: "9",
        engineAdd: "1",
        engineTot: "10",
        mrGboxRem: "6",
        mrGboxAdd: "0",
        mrGboxTot: "6",
        trGboxRem: "4",
        trGboxAdd: "0",
        trGboxTot: "4",
        remarks: "",
        signature: "",
      },
    ],
    componentData: {
      broughtForwardData: {
        airframe: "1300",
        gearBoxMain: "900",
        gearBoxTail: "450",
        rotorMain: "650",
        rotorTail: "325",
        airframeNextInsp: "1600",
        engine: "480",
        cycleN1: "350",
        cycleN2: "350",
        usage: "50",
        landingCycle: "300",
        engineNextInsp: "550",
      },
      thisFlightData: {},
      toDateData: {},
    },
    workItems: [],
    broughtForwardLocked: true,
    notifiedForCompletion: false,
    releasedBy: { name: "", signature: "", timestamp: "" },
    acceptedBy: { name: "", signature: "", timestamp: "" },
  },
  {
    id: "3",
    rpc: "7249",
    aircraftType: "AS350B3E",
    date: "02/22/2026",
    control: "Control value here",
    status: "ongoing",
    createdBy: "pilot",
    dateAdded: "02/22/2026",
    legs: [
      {
        stations: [
          { from: "Cebu", to: "Davao" },
          { from: "Davao", to: "Cebu" },
        ],
        blockTimeOn: "10:00",
        blockTimeOff: "12:30",
        flightTimeOn: "10:15",
        flightTimeOff: "12:15",
        totalTimeOn: "2:00",
        totalTimeOff: "2:00",
        date: "02/22/2026",
        passengers: "15",
      },
    ],
    remarks: "",
    sling: "",
    fuelServicing: [
      {
        date: "02/22/2026",
        contCheck: "OK",
        mainRemG: "200",
        mainAdd: "0",
        mainTotal: "200",
        fuelType: "drum",
        refuelerName: "",
        signature: "",
      },
    ],
    oilServicing: [
      {
        date: "02/22/2026",
        engineRem: "10",
        engineAdd: "0",
        engineTot: "10",
        mrGboxRem: "6",
        mrGboxAdd: "0",
        mrGboxTot: "6",
        trGboxRem: "4",
        trGboxAdd: "0",
        trGboxTot: "4",
        remarks: "",
        signature: "",
      },
    ],
    componentData: {
      broughtForwardData: {
        airframe: "1350",
        gearBoxMain: "950",
        gearBoxTail: "475",
        rotorMain: "680",
        rotorTail: "340",
        airframeNextInsp: "1700",
        engine: "510",
        cycleN1: "380",
        cycleN2: "380",
        usage: "55",
        landingCycle: "320",
        engineNextInsp: "600",
      },
      thisFlightData: {},
      toDateData: {},
    },
    workItems: [],
    broughtForwardLocked: true,
    notifiedForCompletion: false,
    releasedBy: {
      name: "John Mechanic",
      signature: "mock_signature_1",
      timestamp: "2026-02-22T10:00:00Z",
    },
    acceptedBy: { name: "", signature: "", timestamp: "" },
  },
  {
    id: "4",
    rpc: "7250",
    aircraftType: "AS350B3E",
    date: "02/21/2026",
    control: "Control value here",
    status: "completed",
    createdBy: "engineer",
    dateAdded: "02/21/2026",
    legs: [
      {
        stations: [{ from: "Manila", to: "Clark" }],
        blockTimeOn: "14:00",
        blockTimeOff: "14:45",
        flightTimeOn: "14:10",
        flightTimeOff: "14:40",
        totalTimeOn: "0:30",
        totalTimeOff: "0:30",
        date: "02/21/2026",
        passengers: "8",
      },
    ],
    remarks: "Check engine oil level low",
    sling: "Cargo sling used for equipment",
    fuelServicing: [
      {
        date: "02/21/2026",
        contCheck: "OK",
        mainRemG: "120",
        mainAdd: "80",
        mainTotal: "200",
        fuelType: "truck",
        refuelerName: "",
        signature: "mock_signature_2",
      },
    ],
    oilServicing: [
      {
        date: "02/21/2026",
        engineRem: "7",
        engineAdd: "3",
        engineTot: "10",
        mrGboxRem: "5",
        mrGboxAdd: "1",
        mrGboxTot: "6",
        trGboxRem: "3",
        trGboxAdd: "1",
        trGboxTot: "4",
        remarks: "Added oil to engine",
        signature: "mock_signature_3",
      },
    ],
    componentData: {
      broughtForwardData: {
        airframe: "1400",
        gearBoxMain: "1000",
        gearBoxTail: "500",
        rotorMain: "700",
        rotorTail: "350",
        airframeNextInsp: "1800",
        engine: "540",
        cycleN1: "400",
        cycleN2: "400",
        usage: "60",
        landingCycle: "340",
        engineNextInsp: "650",
      },
      thisFlightData: {
        airframe: "1450",
        gearBoxMain: "1050",
        gearBoxTail: "525",
        rotorMain: "730",
        rotorTail: "365",
        airframeNextInsp: "1900",
        engine: "570",
        cycleN1: "430",
        cycleN2: "430",
        usage: "65",
        landingCycle: "360",
        engineNextInsp: "700",
      },
      toDateData: {
        airframe: "2850",
        gearBoxMain: "2050",
        gearBoxTail: "1025",
        rotorMain: "1430",
        rotorTail: "715",
        airframeNextInsp: "3700",
        engine: "1110",
        cycleN1: "830",
        cycleN2: "830",
        usage: "125",
        landingCycle: "700",
        engineNextInsp: "1350",
      },
    },
    workItems: [
      {
        id: "work1",
        selectedWorkTypes: ["Discrepancy Correction"],
        date: "02/21/2026",
        aircraft: "AS350B3E",
        workDone: "Added oil to engine, checked for leaks",
        name: "John Mechanic",
        certificateNumber: "A&P-12345",
        signature: "mock_signature_4",
      },
    ],
    broughtForwardLocked: true,
    notifiedForCompletion: true,
    releasedBy: {
      name: "John Mechanic",
      signature: "mock_signature_1",
      timestamp: "2026-02-21T15:00:00Z",
    },
    acceptedBy: {
      name: "Jane Pilot",
      signature: "mock_signature_5",
      timestamp: "2026-02-21T16:00:00Z",
    },
  },
  {
    id: "5",
    rpc: "7251",
    aircraftType: "AS350B3E",
    date: "02/20/2026",
    control: "Control value here",
    status: "ongoing",
    createdBy: "pilot",
    dateAdded: "02/20/2026",
    legs: [
      {
        stations: [{ from: "Clark", to: "Subic" }],
        blockTimeOn: "09:00",
        blockTimeOff: "09:30",
        flightTimeOn: "09:05",
        flightTimeOff: "09:25",
        totalTimeOn: "0:20",
        totalTimeOff: "0:20",
        date: "02/20/2026",
        passengers: "6",
      },
    ],
    remarks: "GPS interference during approach",
    sling: "",
    fuelServicing: [
      {
        date: "02/20/2026",
        contCheck: "OK",
        mainRemG: "160",
        mainAdd: "40",
        mainTotal: "200",
        fuelType: "drum",
        refuelerName: "",
        signature: "",
      },
    ],
    oilServicing: [
      {
        date: "02/20/2026",
        engineRem: "8",
        engineAdd: "2",
        engineTot: "10",
        mrGboxRem: "5",
        mrGboxAdd: "1",
        mrGboxTot: "6",
        trGboxRem: "3",
        trGboxAdd: "1",
        trGboxTot: "4",
        remarks: "",
        signature: "",
      },
    ],
    componentData: {
      broughtForwardData: {
        airframe: "1250",
        gearBoxMain: "850",
        gearBoxTail: "425",
        rotorMain: "620",
        rotorTail: "310",
        airframeNextInsp: "1500",
        engine: "450",
        cycleN1: "320",
        cycleN2: "320",
        usage: "45",
        landingCycle: "280",
        engineNextInsp: "500",
      },
      thisFlightData: {},
      toDateData: {},
    },
    workItems: [],
    broughtForwardLocked: false,
    notifiedForCompletion: false,
    releasedBy: { name: "", signature: "", timestamp: "" },
    acceptedBy: { name: "", signature: "", timestamp: "" },
  },
];
