const mongoose = require("mongoose");

const signatureSchema = new mongoose.Schema(
  {
    name: { type: String, default: "" },
    id: { type: String, default: "" },
    timestamp: { type: String, default: "" },
  },
  { _id: false },
);

const postInspectionSchema = new mongoose.Schema(
  {
    preInspectionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "PreInspection",
      default: null,
      index: true,
    },
    linkedFromPreFlight: {
      type: Boolean,
      default: false,
    },
    aircraftType: { type: String, required: true, trim: true },
    rpc: { type: String, required: true, trim: true },
    date: { type: String, required: true },
    dateAdded: { type: String, default: "" },
    createdBy: { type: String, default: "" },
    status: {
      type: String,
      enum: ["pending", "completed"],
      default: "pending",
    },
    station1_transparentPanels_condition: { type: Boolean, default: false },
    station1_transparentPanels_clean: { type: Boolean, default: false },
    station1_doorsPillars_condition: { type: Boolean, default: false },
    station1_sideSlipIndicator_condition: { type: Boolean, default: false },
    station1_sideSlipIndicator2_condition: { type: Boolean, default: false },
    station1_mgbEngineOilCooler_condition: { type: Boolean, default: false },
    station2_frontDoorJettison_condition: { type: Boolean, default: false },
    station2_leftCabinAccess_condition: { type: Boolean, default: false },
    station2_landingGear_condition: { type: Boolean, default: false },
    station2_staticPressure_condition: { type: Boolean, default: false },
    station2_oatProbe_condition: { type: Boolean, default: false },
    station2_antennas_condition: { type: Boolean, default: false },
    station2_lights_condition: { type: Boolean, default: false },
    station2_lowerCowlings_condition: { type: Boolean, default: false },
    station2_leftCargoDoorOpen_opening: { type: Boolean, default: false },
    station2_leftCargoDoorClosed_closed: { type: Boolean, default: false },
    station2_fuelTank_condition: { type: Boolean, default: false },
    station2_rearCargoDoorOpen_opening: { type: Boolean, default: false },
    station2_rearCargoBay_harness: { type: Boolean, default: false },
    station2_elt_condition: { type: Boolean, default: false },
    station2_rearCargoDoorClosed_closed: { type: Boolean, default: false },
    station2_mgbCowlings_opening: { type: Boolean, default: false },
    station2_upperCowling_security: { type: Boolean, default: false },
    station2_mgb_condition: { type: Boolean, default: false },
    station2_transmissionDeck_cleanliness: { type: Boolean, default: false },
    station2_mgbSupportBars_condition: { type: Boolean, default: false },
    station2_hydraulicSystem_condition: { type: Boolean, default: false },
    station2_servos_security: { type: Boolean, default: false },
    station2_coolingFan_condition: { type: Boolean, default: false },
    station2_gimbalRing_fitting: { type: Boolean, default: false },
    station2_electricalHarnesses_condition: { type: Boolean, default: false },
    station2_fuelShutoff_condition: { type: Boolean, default: false },
    station2_mgbCowlingLH_safety: { type: Boolean, default: false },
    engine_airInlet_condition: { type: Boolean, default: false },
    engine_firewall_condition: { type: Boolean, default: false },
    engine_accessories_condition: { type: Boolean, default: false },
    engine_transmissionDeck_condition: { type: Boolean, default: false },
    engine_case_condition: { type: Boolean, default: false },
    engine_oilFilter_condition: { type: Boolean, default: false },
    engine_fuelFilter_condition: { type: Boolean, default: false },
    engine_oilSystem_condition: { type: Boolean, default: false },
    engine_mounts_condition: { type: Boolean, default: false },
    engine_deckDrainHoles_condition: { type: Boolean, default: false },
    engine_exhaustPipe_condition: { type: Boolean, default: false },
    station3_scissors_condition: { type: Boolean, default: false },
    station3_swashPlate_condition: { type: Boolean, default: false },
    station3_pitchChangeRods_condition: { type: Boolean, default: false },
    station3_rotorShaft_condition: { type: Boolean, default: false },
    mainRotor_head_condition: { type: Boolean, default: false },
    mainRotor_starflex_condition: { type: Boolean, default: false },
    mainRotor_starRecesses_condition: { type: Boolean, default: false },
    mainRotor_sphericalBearings_condition: { type: Boolean, default: false },
    mainRotor_ballJoints_condition: { type: Boolean, default: false },
    mainRotor_starArms_condition: { type: Boolean, default: false },
    mainRotor_vibrationAbsorber_condition: { type: Boolean, default: false },
    mainRotor_blades_condition: { type: Boolean, default: false },
    mainRotor_rightCargoDoor_opening: { type: Boolean, default: false },
    mainRotor_rightCargoDoor_closed: { type: Boolean, default: false },
    mainRotor_gpuPlug_condition: { type: Boolean, default: false },
    mainRotor_rhMgbCowling_opening: { type: Boolean, default: false },
    mainRotor_transmissionDeck_cleanliness: { type: Boolean, default: false },
    mainRotor_mgbSupportBars_condition: { type: Boolean, default: false },
    mainRotor_oilCooler_condition: { type: Boolean, default: false },
    mainRotor_servos_security: { type: Boolean, default: false },
    mainRotor_hydraulicSystem_condition: { type: Boolean, default: false },
    mainRotor_hydraulicTank_condition: { type: Boolean, default: false },
    mainRotor_engineOilTank_condition: { type: Boolean, default: false },
    mainRotor_electricalHarnesses_condition: { type: Boolean, default: false },
    mainRotor_gimbalRing_fitting: { type: Boolean, default: false },
    mainRotor_rhSideMgbCowling_closed: { type: Boolean, default: false },
    mainRotor_landingGear_condition: { type: Boolean, default: false },
    mainRotor_lowerFairings_closed: { type: Boolean, default: false },
    mainRotor_rhCabinAccess_condition: { type: Boolean, default: false },
    mainRotor_frontDoorJettison_condition: { type: Boolean, default: false },
    cabin_general_cleanliness: { type: Boolean, default: false },
    cabin_seats_condition: { type: Boolean, default: false },
    cabin_doorJettison_checked: { type: Boolean, default: false },
    cabin_fireExtinguisher_condition: { type: Boolean, default: false },
    cabin_circuitBreakers_set: { type: Boolean, default: false },
    cabin_scu_position: { type: Boolean, default: false },
    cabin_batterySwitchOn_on: { type: Boolean, default: false },
    cabin_vemd_flightReport: { type: Boolean, default: false },
    cabin_vemd_flightTimes: { type: Boolean, default: false },
    cabin_vemd_cycles: { type: Boolean, default: false },
    cabin_vemd_advisoryMessages: { type: Boolean, default: false },
    cabin_vemd_recordData: { type: Boolean, default: false },
    cabin_batterySwitchOff_off: { type: Boolean, default: false },
    releasedBy: { type: signatureSchema, default: () => ({}) },
  },
  { collection: "post_inspections", timestamps: true },
);

module.exports = mongoose.model("PostInspection", postInspectionSchema);
