const mongoose = require("mongoose");

const signatureSchema = new mongoose.Schema(
  {
    name: { type: String, default: "" },
    id: { type: String, default: "" },
    timestamp: { type: String, default: "" },
  },
  { _id: false },
);

const preInspectionSchema = new mongoose.Schema(
  {
    aircraftType: { type: String, required: true, trim: true },
    rpc: { type: String, required: true, trim: true },
    date: { type: String, required: true },
    dateAdded: { type: String, default: "" },
    createdBy: { type: String, default: "" },
    status: {
      type: String,
      enum: ["pending", "released", "completed"],
      default: "pending",
    },
    station1_transparentPanels: { type: Boolean, default: false },
    station1_engineOilCooler: { type: Boolean, default: false },
    station1_sideSlipIndicator: { type: Boolean, default: false },
    station1_pitotTube: { type: Boolean, default: false },
    station1_landingLights: { type: Boolean, default: false },
    station1_mgbCowl: { type: Boolean, default: false },
    station1_lowerFairings: { type: Boolean, default: false },
    station1_landingGear: { type: Boolean, default: false },
    station1_staticPorts: { type: Boolean, default: false },
    station1_oatSensor: { type: Boolean, default: false },
    station1_mainRotor: { type: Boolean, default: false },
    station1_engineAirIntake: { type: Boolean, default: false },
    station1_engineCowl: { type: Boolean, default: false },
    station1_exhaustCover: { type: Boolean, default: false },
    station1_rearCargoDoorOpen: { type: Boolean, default: false },
    station1_loadsObjects: { type: Boolean, default: false },
    station1_elt: { type: Boolean, default: false },
    station1_rearCargoDoorClosed: { type: Boolean, default: false },
    station1_oilDrain: { type: Boolean, default: false },
    station2_frontDoor: { type: Boolean, default: false },
    station2_rearDoor: { type: Boolean, default: false },
    station2_leftCargoDoorOpen: { type: Boolean, default: false },
    station2_loadsObjects: { type: Boolean, default: false },
    station2_leftCargoDoorClosed: { type: Boolean, default: false },
    station2_fuelTank: { type: Boolean, default: false },
    station3_heatShield: { type: Boolean, default: false },
    station3_tailBoom: { type: Boolean, default: false },
    station3_stabilizer: { type: Boolean, default: false },
    station3_tailRotorGuard: { type: Boolean, default: false },
    station3_tgbFairing: { type: Boolean, default: false },
    station3_tgbOilLevel: { type: Boolean, default: false },
    station3_tailSkid: { type: Boolean, default: false },
    station3_flexibleCoupling: { type: Boolean, default: false },
    sling_sling: { type: Boolean, default: false },
    sling_cablePins: { type: Boolean, default: false },
    floats_lhRh: { type: Boolean, default: false },
    floats_cylinder: { type: Boolean, default: false },
    floats_hoses: { type: Boolean, default: false },
    onboard_firstAid: { type: Boolean, default: false },
    onboard_lifeVest: { type: Boolean, default: false },
    onboard_lifeRaft: { type: Boolean, default: false },
    onboard_axl: { type: Boolean, default: false },
    onboard_fireExt: { type: Boolean, default: false },
    onboard_certAirworthiness: { type: Boolean, default: false },
    onboard_certRegistration: { type: Boolean, default: false },
    onboard_radioLicense: { type: Boolean, default: false },
    onboard_flightLogbook: { type: Boolean, default: false },
    fob: { type: String, default: "" },
    releasedBy: { type: signatureSchema, default: () => ({}) },
    acceptedBy: { type: signatureSchema, default: () => ({}) },
  },
  { collection: "pre_inspections", timestamps: true },
);

module.exports = mongoose.model("PreInspection", preInspectionSchema);
