export const flightLogsMockData = [
  {
    id: "1",
    rpc: "7247",
    aircraftType: "AS350B3E",
    date: "02/24/2026",
    control: "Control value here",
    status: "pending_release",
    createdBy: "pilot",
    dateAdded: "02/24/2026",
    tailNum: "7247",
    depart: "MNL",
    arrive: "CEB",
    offBlock: "08:00",
    onBlock: "09:30",
    blockTime: "1:30",
    flightTime: "1:15",
    technicalAction: "Routine check",
    legs: [
      {
        stations: [{ from: "Manila", to: "Cebu" }],
        blockTimeOn: "08:00",
        blockTimeOff: "09:30",
        flightTimeOn: "08:15",
        flightTimeOff: "09:15",
        totalTimeOn: "1:00",
        totalTimeOff: "1:00",
        date: "02/24/2026",
        passengers: "12",
      }
    ],
    remarks: "Minor vibration noticed during climb",
    sling: "",
  },
  {
    id: "2",
    rpc: "7248",
    aircraftType: "AS350B3E",
    date: "02/23/2026",
    control: "Control value here",
    status: "pending_acceptance",
    createdBy: "mechanic",
    dateAdded: "02/23/2026",
    tailNum: "7248",
    depart: "CEB",
    arrive: "DVO",
    offBlock: "10:00",
    onBlock: "12:30",
    blockTime: "2:30",
    flightTime: "2:15",
    technicalAction: "Routine check",
    legs: [],
    remarks: "",
    sling: "",
  },
  {
    id: "3",
    rpc: "7249",
    aircraftType: "AS350B3E",
    date: "02/22/2026",
    control: "Control value here",
    status: "ongoing",
    createdBy: "pilot",
    dateAdded: "02/22/2026",
    tailNum: "7249",
    depart: "DVO",
    arrive: "MNL",
    offBlock: "14:00",
    onBlock: "16:30",
    blockTime: "2:30",
    flightTime: "2:15",
    technicalAction: "Routine check",
    legs: [
      {
        stations: [{ from: "Davao", to: "Manila" }],
        blockTimeOn: "14:00",
        blockTimeOff: "16:30",
        flightTimeOn: "14:15",
        flightTimeOff: "16:15",
        totalTimeOn: "2:00",
        totalTimeOff: "2:00",
        date: "02/22/2026",
        passengers: "15",
      }
    ],
    remarks: "",
    sling: "",
  },
  {
    id: "4",
    rpc: "7250",
    aircraftType: "AS350B3E",
    date: "02/21/2026",
    control: "Control value here",
    status: "completed",
    createdBy: "mechanic",
    dateAdded: "02/21/2026",
    tailNum: "7250",
    depart: "MNL",
    arrive: "CRK",
    offBlock: "14:00",
    onBlock: "14:45",
    blockTime: "0:45",
    flightTime: "0:30",
    technicalAction: "Completed",
    legs: [
      {
        stations: [{ from: "Manila", to: "Clark" }],
        blockTimeOn: "14:00",
        blockTimeOff: "14:45",
        flightTimeOn: "14:10",
        flightTimeOff: "14:40",
        totalTimeOn: "0:30",
        totalTimeOff: "0:30",
        date: "02/21/2026",
        passengers: "8",
      }
    ],
    remarks: "Check engine oil level low",
    sling: "Cargo sling used for equipment",
  },
  {
    id: "5",
    rpc: "7251",
    aircraftType: "AS350B3E",
    date: "02/20/2026",
    control: "Control value here",
    status: "ongoing",
    createdBy: "pilot",
    dateAdded: "02/20/2026",
    tailNum: "7251",
    depart: "CRK",
    arrive: "SFS",
    offBlock: "09:00",
    onBlock: "09:30",
    blockTime: "0:30",
    flightTime: "0:20",
    technicalAction: "Routine check",
    legs: [
      {
        stations: [{ from: "Clark", to: "Subic" }],
        blockTimeOn: "09:00",
        blockTimeOff: "09:30",
        flightTimeOn: "09:05",
        flightTimeOff: "09:25",
        totalTimeOn: "0:20",
        totalTimeOff: "0:20",
        date: "02/20/2026",
        passengers: "6",
      }
    ],
    remarks: "GPS interference during approach",
    sling: "",
  },
];