const TaskInfo = [
  {
    id: "1",
    status: "Pending",
    title: "Engine Inspection",
    aircraft: "2810",
    dueDate: "2026-02-25",
    startDateTime: "",
    endDateTime: "",
    priority: "Due Soon",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "1",
    assignedToName: "John Doe",
    checklistItems: [
      "Inspect oil level",
      "Check spark plugs",
      "Inspect fuel lines",
      "Test engine compression",
    ],
  },
  {
    id: "2",
    status: "Ongoing",
    title: "Landing Gear Maintenance",
    aircraft: "2811",
    dueDate: "2026-02-28",
    startDateTime: "2026-02-18 09:00 AM",
    endDateTime: "",
    priority: "Normal",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "2",
    assignedToName: "Clara Bang",
    checklistItems: [
      "Inspect struts",
      "Check hydraulic fluid",
      "Test landing gear extension/retraction",
    ],
  },
  {
    id: "3",
    status: "Turned in",
    title: "Avionics System Check",
    aircraft: "2812",
    dueDate: "2026-02-22",
    startDateTime: "2026-02-19 10:00 AM",
    endDateTime: "2026-02-19 01:00 PM",
    priority: "Overdue",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "1",
    assignedToName: "John Doe",
    checklistItems: [
      "Test radios",
      "Check GPS navigation",
      "Inspect cockpit displays",
    ],
  },
  {
    id: "4",
    status: "Pending",
    title: "Fuel System Leak Inspection",
    aircraft: "2810",
    dueDate: "2026-03-01",
    startDateTime: "",
    endDateTime: "",
    priority: "Normal",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "3",
    assignedToName: "Joe Bloggs",
    checklistItems: [
      "Inspect fuel tanks",
      "Check fuel lines",
      "Pressure test fuel system",
    ],
  },
  {
    id: "5",
    status: "Ongoing",
    title: "Hydraulic Pump Replacement",
    aircraft: "2812",
    dueDate: "2026-02-26",
    startDateTime: "2026-02-18 08:00 AM",
    endDateTime: "",
    priority: "Due Soon",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "2",
    assignedToName: "Clara Bang",
    checklistItems: [
      "Remove old pump",
      "Install new pump",
      "Bleed hydraulic system",
      "Test hydraulic pressure",
    ],
  },
  {
    id: "6",
    status: "Turned in",
    title: "Oil Filter Replacement",
    aircraft: "2810",
    dueDate: "2026-02-15",
    startDateTime: "2026-02-15 09:00 AM",
    endDateTime: "2026-02-15 10:30 AM",
    priority: "Normal",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "4",
    assignedToName: "Max Miller",
    checklistItems: [
      "Drain old oil",
      "Remove old filter",
      "Install new filter",
      "Refill oil",
    ],
  },
  {
    id: "7",
    status: "Pending",
    title: "Brake System Check",
    aircraft: "2811",
    dueDate: "2026-03-03",
    startDateTime: "",
    endDateTime: "",
    priority: "Normal",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "5",
    assignedToName: "Liam Brown",
    checklistItems: [
      "Inspect brake pads",
      "Check brake fluid",
      "Test brake operation",
    ],
  },
  {
    id: "8",
    status: "Ongoing",
    title: "Electrical Wiring Inspection",
    aircraft: "2812",
    dueDate: "2026-02-27",
    startDateTime: "2026-02-18 10:00 AM",
    endDateTime: "",
    priority: "Due Soon",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "6",
    assignedToName: "Dilan Wolf",
    checklistItems: [
      "Check battery connections",
      "Inspect wiring harness",
      "Test lighting circuits",
    ],
  },
  {
    id: "9",
    status: "Turned in",
    title: "Propeller Balancing",
    aircraft: "2811",
    dueDate: "2026-02-14",
    startDateTime: "2026-02-14 08:30 AM",
    endDateTime: "2026-02-14 12:00 PM",
    priority: "Normal",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "7",
    assignedToName: "Bob Rosfield",
    checklistItems: [
      "Remove propeller",
      "Mount on balancing machine",
      "Adjust weight as necessary",
    ],
  },
  {
    id: "10",
    status: "Pending",
    title: "Cabin Pressure Test",
    aircraft: "2810",
    dueDate: "2026-03-15",
    startDateTime: "",
    endDateTime: "",
    priority: "Normal",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "1",
    assignedToName: "John Doe",
    checklistItems: [
      "Seal cabin",
      "Pressurize system",
      "Check for leaks",
      "Record pressure readings",
    ],
  },
  {
    id: "11",
    status: "Returned",
    title: "Landing Light Replacement",
    aircraft: "2812",
    dueDate: "2026-03-02",
    startDateTime: "2026-02-26 08:00 AM",
    endDateTime: "",
    priority: "Normal",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "2",
    assignedToName: "Clara Bang",
    checklistItems: ["Remove old bulb", "Install new bulb", "Test operation"],
  },
  {
    id: "12",
    status: "Returned",
    title: "Landing Gear Hydraulic Leak Check",
    aircraft: "2811",
    dueDate: "2026-03-15",
    startDateTime: "2026-03-10 09:00 AM",
    endDateTime: "",
    priority: "Normal",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "3",
    assignedToName: "Joe Bloggs",
    checklistItems: [
      "Inspect hydraulic lines",
      "Check fluid level",
      "Test for leaks",
      "Verify pressure",
    ],
  },
  {
    id: "13",
    status: "Returned",
    title: "Avionics Software Update",
    aircraft: "2812",
    dueDate: "2026-02-28",
    startDateTime: "2026-02-25 01:00 PM",
    endDateTime: "",
    priority: "Due Soon",
    maintenanceType: "Corrective Maintenance",
    assignedTo: "4",
    assignedToName: "Max Miller",
    checklistItems: [
      "Update navigation database",
      "Verify system functionality",
      "Test all instruments",
    ],
  },
];

export default TaskInfo;