const TaskInfo = [
  {
    id: "1",
    status: "Pending",
    title: "Engine Inspection - Cessna 172",
    dueDate: "2026-02-25",
    startDateTime: "2026-02-20 08:00 AM",
    endDateTime: "2026-02-20 12:00 PM",
    priority: "Due Soon",
    checklistItems: [
      "Inspect oil level",
      "Check spark plugs",
      "Inspect fuel lines",
      "Test engine compression",
    ],
  },
  {
    id: "2",
    status: "Ongoing",
    title: "Landing Gear Maintenance - Piper PA-28",
    dueDate: "2026-02-28",
    startDateTime: "2026-02-18 09:00 AM",
    endDateTime: "2026-02-18 03:00 PM",
    priority: "Normal",
    checklistItems: [
      "Inspect struts",
      "Check hydraulic fluid",
      "Test landing gear extension/retraction",
    ],
  },
  {
    id: "3",
    status: "Completed",
    title: "Avionics System Check - Beechcraft King Air",
    dueDate: "2026-02-22",
    startDateTime: "2026-02-19 10:00 AM",
    endDateTime: "2026-02-19 01:00 PM",
    priority: "Overdue",
    checklistItems: [
      "Test radios",
      "Check GPS navigation",
      "Inspect cockpit displays",
    ],
  },
  {
    id: "4",
    status: "Pending",
    title: "Fuel System Leak Inspection - Diamond DA40",
    dueDate: "2026-03-01",
    startDateTime: "2026-02-24 07:30 AM",
    endDateTime: "2026-02-24 11:30 AM",
    priority: "Normal",
    checklistItems: [
      "Inspect fuel tanks",
      "Check fuel lines",
      "Pressure test fuel system",
    ],
  },
  {
    id: "5",
    status: "Ongoing",
    title: "Hydraulic Pump Replacement - Airbus H125",
    dueDate: "2026-02-26",
    startDateTime: "2026-02-18 08:00 AM",
    endDateTime: "2026-02-18 05:00 PM",
    priority: "Due Soon",
    checklistItems: [
      "Remove old pump",
      "Install new pump",
      "Bleed hydraulic system",
      "Test hydraulic pressure",
    ],
  },
  {
    id: "6",
    status: "Completed",
    title: "Oil Filter Replacement - Cessna 208 Caravan",
    dueDate: "2026-02-15",
    startDateTime: "2026-02-15 09:00 AM",
    endDateTime: "2026-02-15 10:30 AM",
    priority: "Normal",
    checklistItems: [
      "Drain old oil",
      "Remove old filter",
      "Install new filter",
      "Refill oil",
    ],
  },
  {
    id: "7",
    status: "Pending",
    title: "Brake System Check - Piper Seneca",
    dueDate: "2026-03-03",
    startDateTime: "2026-02-27 01:00 PM",
    endDateTime: "2026-02-27 04:00 PM",
    priority: "Normal",
    checklistItems: [
      "Inspect brake pads",
      "Check brake fluid",
      "Test brake operation",
    ],
  },
  {
    id: "8",
    status: "Ongoing",
    title: "Electrical Wiring Inspection - Beechcraft Baron",
    dueDate: "2026-02-27",
    startDateTime: "2026-02-18 10:00 AM",
    endDateTime: "2026-02-18 06:00 PM",
    priority: "Due Soon",
    checklistItems: [
      "Check battery connections",
      "Inspect wiring harness",
      "Test lighting circuits",
    ],
  },
  {
    id: "9",
    status: "Completed",
    title: "Propeller Balancing - Cessna 182",
    dueDate: "2026-02-14",
    startDateTime: "2026-02-14 08:30 AM",
    endDateTime: "2026-02-14 12:00 PM",
    priority: "Normal",
    checklistItems: [
      "Remove propeller",
      "Mount on balancing machine",
      "Adjust weight as necessary",
    ],
  },
  {
    id: "10",
    status: "Pending",
    title: "Cabin Pressure Test - Beechcraft King Air 350",
    dueDate: "2026-03-05",
    startDateTime: "2026-02-28 09:00 AM",
    endDateTime: "2026-02-28 02:00 PM",
    priority: "Normal",
    checklistItems: [
      "Seal cabin",
      "Pressurize system",
      "Check for leaks",
      "Record pressure readings",
    ],
  },
];
export default TaskInfo;
