const path = require("path");

require("dotenv").config({
  path: path.join(__dirname, "..", ".env"),
  quiet: true,
});

const mongoose = require("mongoose");

const CONFIRMATION_PHRASE = "DELETE_ALL_AIRCRAFT_DATA";

const OPERATIONAL_NOTIFICATION_FILTER = {
  $or: [
    {
      module: {
        $in: [
          "parts-requisition",
          "flight-logs",
          "pre-flight inspections",
          "post-flight inspections",
          "tasks",
        ],
      },
    },
    {
      entityType: {
        $in: [
          "parts-requisition",
          "flight-log",
          "pre-flight inspection",
          "post-flight inspection",
          "task",
        ],
      },
    },
  ],
};

// Delete dependent records first and the aircraft registry last. These names
// match the collections generated by the Mongoose models in server/models.
const AIRCRAFT_DATA_TARGETS = Object.freeze([
  { collection: "notifications", filter: OPERATIONAL_NOTIFICATION_FILTER },
  { collection: "aiinsightcaches", filter: {} },
  { collection: "airectifications", filter: {} },
  { collection: "maintenancelogs", filter: {} },
  { collection: "technicallogs", filter: {} },
  { collection: "partsrequisitions", filter: {} },
  { collection: "tasks", filter: {} },
  { collection: "pre_inspections", filter: {} },
  { collection: "post_inspections", filter: {} },
  { collection: "flightlogs", filter: {} },
  { collection: "partslifespanmonitorings", filter: {} },
  { collection: "aircrafts", filter: {} },
]);

const PRESERVED_DATA = Object.freeze([
  "users, sessions, and refresh tokens",
  "messages and conversations",
  "message notifications",
  "user, admin, and security audit logs",
  "inspection schedules and inspection-task templates",
  "maintenance-priority rules",
  "manual rules and procedures",
  "station-level approved technical logs",
]);

const readOption = (args, name) => {
  const prefix = `${name}=`;
  const option = args.find((argument) => argument.startsWith(prefix));
  return option ? option.slice(prefix.length).trim() : "";
};

const parseArguments = (args) => {
  const knownFlags = new Set([
    "--dry-run",
    "--execute",
    "--backup-confirmed",
    "--help",
  ]);
  const unknown = args.filter(
    (argument) =>
      !knownFlags.has(argument) &&
      !argument.startsWith("--confirm=") &&
      !argument.startsWith("--database="),
  );

  if (unknown.length > 0) {
    throw new Error(`Unknown argument(s): ${unknown.join(", ")}`);
  }

  const execute = args.includes("--execute");
  if (execute && args.includes("--dry-run")) {
    throw new Error("Choose either --dry-run or --execute, not both.");
  }

  return {
    execute,
    backupConfirmed: args.includes("--backup-confirmed"),
    confirmation: readOption(args, "--confirm"),
    expectedDatabase: readOption(args, "--database"),
    help: args.includes("--help"),
  };
};

const validateExecution = (options, actualDatabase) => {
  if (!options.execute) return;

  if (!options.backupConfirmed) {
    throw new Error(
      "Execution refused. Create a database backup, then include --backup-confirmed.",
    );
  }

  if (options.confirmation !== CONFIRMATION_PHRASE) {
    throw new Error(
      `Execution refused. Pass --confirm=${CONFIRMATION_PHRASE} exactly.`,
    );
  }

  if (!options.expectedDatabase) {
    throw new Error(
      `Execution refused. Pass --database=${actualDatabase} to confirm the target database.`,
    );
  }

  if (options.expectedDatabase !== actualDatabase) {
    throw new Error(
      `Execution refused. Connected to database "${actualDatabase}", not "${options.expectedDatabase}".`,
    );
  }
};

const getMongoUrl = () =>
  process.env.ATLAS_URL || process.env.MONGODB_URI || process.env.MONGO_URI || "";

const countTargets = async (database) => {
  const counts = [];
  for (const target of AIRCRAFT_DATA_TARGETS) {
    counts.push({
      collection: target.collection,
      documents: await database
        .collection(target.collection)
        .countDocuments(target.filter),
    });
  }

  return counts;
};

const deleteTargets = async (database, session) => {
  const results = [];
  for (const target of AIRCRAFT_DATA_TARGETS) {
    const result = await database
      .collection(target.collection)
      .deleteMany(target.filter, { session });
    results.push({
      collection: target.collection,
      deletedDocuments: result.deletedCount,
    });
  }

  return results;
};

const printUsage = () => {
  console.log(`Aircraft data cleanup

Dry run (default):
  npm run cleanup:aircraft

Permanent cleanup after making a backup:
  npm run cleanup:aircraft -- --execute --backup-confirmed --database=<database-name> --confirm=${CONFIRMATION_PHRASE}

The dry run prints the connected database name and document counts needed for
the permanent command. No data is changed unless every execution guard passes.`);
};

const main = async (args = process.argv.slice(2)) => {
  const options = parseArguments(args);
  if (options.help) {
    printUsage();
    return;
  }

  const mongoUrl = getMongoUrl();
  if (!mongoUrl) {
    throw new Error(
      "Missing ATLAS_URL, MONGODB_URI, or MONGO_URI in server/.env.",
    );
  }

  await mongoose.connect(mongoUrl, {
    serverSelectionTimeoutMS: 15000,
    socketTimeoutMS: 45000,
    family: 4,
  });

  const database = mongoose.connection.db;
  const databaseName = mongoose.connection.name;
  const before = await countTargets(database);
  const totalBefore = before.reduce((total, item) => total + item.documents, 0);

  console.log(
    JSON.stringify(
      {
        mode: options.execute ? "execute" : "dry-run",
        database: databaseName,
        targetedDocuments: totalBefore,
        targets: before,
        preservedData: PRESERVED_DATA,
      },
      null,
      2,
    ),
  );

  if (!options.execute) {
    console.log(
      `Dry run only. After backing up, rerun with --execute --backup-confirmed --database=${databaseName} --confirm=${CONFIRMATION_PHRASE}`,
    );
    return;
  }

  validateExecution(options, databaseName);

  const session = await mongoose.connection.startSession();
  let deleted = [];
  try {
    await session.withTransaction(async () => {
      deleted = await deleteTargets(database, session);
    });
  } finally {
    await session.endSession();
  }

  const after = await countTargets(database);
  const remainingDocuments = after.reduce(
    (total, item) => total + item.documents,
    0,
  );

  console.log(
    JSON.stringify(
      {
        mode: "complete",
        database: databaseName,
        deletedDocuments: deleted.reduce(
          (total, item) => total + item.deletedDocuments,
          0,
        ),
        deleted,
        remainingTargetedDocuments: remainingDocuments,
        remaining: after,
      },
      null,
      2,
    ),
  );

  if (remainingDocuments !== 0) {
    throw new Error(
      `${remainingDocuments} targeted document(s) remain after cleanup. Review the reported collections.`,
    );
  }
};

if (require.main === module) {
  main()
    .catch((error) => {
      console.error(`Aircraft cleanup failed: ${error.message}`);
      process.exitCode = 1;
    })
    .finally(async () => {
      if (mongoose.connection.readyState !== 0) {
        await mongoose.disconnect();
      }
    });
}

module.exports = {
  AIRCRAFT_DATA_TARGETS,
  CONFIRMATION_PHRASE,
  PRESERVED_DATA,
  parseArguments,
  validateExecution,
};
