// Run from the repository root: node server/scripts/updateFlightStationPlaces.js
// Refreshes bundled suggestions; the clients never need these services at runtime.
const fs = require('node:fs/promises');
const path = require('node:path');
const JSZip = require('jszip');

const sources = {
  provinces: 'https://psgc.cloud/api/provinces',
  cities: 'https://psgc.cloud/api/cities',
  islands: 'https://download.geonames.org/export/dump/PH.zip',
};

function cleanName(value) {
  // Some PSGC Cloud names contain UTF-8 decoded as Latin-1 (e.g. Biñan).
  let name = /[\u00c2\u00c3]/.test(value) ? Buffer.from(value, 'latin1').toString('utf8') : value;
  return name.normalize('NFC').replace(/\s+/g, ' ').trim();
}

async function download(url) {
  const response = await fetch(url, { signal: AbortSignal.timeout(60000) });
  if (!response.ok) throw new Error(`${url}: ${response.status}`);
  return response;
}

async function main() {
  const [provinces, cities, archive] = await Promise.all([
    download(sources.provinces).then(r => r.json()),
    download(sources.cities).then(r => r.json()),
    download(sources.islands).then(r => r.arrayBuffer()).then(JSZip.loadAsync),
  ]);
  // Carmona is absent from this mirror. Confirmed in the PSA city directory:
  // https://psa.gov.ph/classification/psgc/cities
  if (!cities.some(city => city.code === '0402104000')) cities.push({ name: 'City of Carmona' });
  const islandRows = (await archive.file('PH.txt').async('string')).trim().split('\n')
    .map(row => row.split('\t'))
    .filter(row => row[8] === 'PH' && ['ISL', 'ISLS'].includes(row[7]) && !row[1].includes(','));
  const cityNames = cities.map(city => cleanName(city.name)
    .replace(/^(?:Island Garden |Science )?City of /i, '')
    .replace(/(?<!Quezon) City$/i, '')
    .replace(/\b(De|Del)\b/g, word => word.toLowerCase()));
  const islandNames = islandRows.map(row => cleanName(row[1]).replace(/ (?:Islands?|Islets?)$/i, ''));
  const names = [...new Set([...provinces.map(row => cleanName(row.name)), ...cityNames, ...islandNames])]
    .sort((a, b) => a.localeCompare(b, 'en'));
  if (provinces.length < 82 || cities.length < 149 || islandRows.length < 2500) throw new Error('Incomplete source data; refusing to replace station names.');
  const header = `// Generated by server/scripts/updateFlightStationPlaces.js on ${new Date().toISOString().slice(0, 10)}.\n`
    + `// Province/city names: ${sources.provinces} and ${sources.cities}; Carmona: PSA city directory.\n`
    + `// Named islands: GeoNames (${sources.islands}), CC BY 4.0: https://creativecommons.org/licenses/by/4.0/\n`
    + '// Names shortened by removing generic City of / Island labels; duplicate names merged.\n'
    + '// This gazetteer is not an exhaustive inventory of every Philippine island. Custom stations remain allowed.\n';
  await fs.writeFile(path.resolve(__dirname, '../../shared/philippineStationNames.js'),
    `${header}export const PHILIPPINE_STATION_NAMES = ${JSON.stringify(['Local', ...names], null, 2)};\n`);
  console.log(`Bundled ${names.length + 1} unique names from ${provinces.length} provinces, ${cities.length} cities and ${islandRows.length} named island/group records.`);
}

main().catch(error => { console.error(error); process.exitCode = 1; });
