export const getDefaultPostInspectionSignature = () => ({
  name: "",
  id: "",
  signature: "",
  timestamp: "",
});

export const getDefaultPostInspectionFormData = (userRole = "") => ({
  aircraftType: "",
  rpc: "",
  date: new Date().toLocaleDateString("en-US"),
  createdBy: userRole,
  status: "pending",
  releasedBy: getDefaultPostInspectionSignature(),
  acceptedBy: getDefaultPostInspectionSignature(),
  station1_transparentPanels_condition: false,
  station1_transparentPanels_clean: false,
  station1_doorsPillars_condition: false,
  station1_sideSlipIndicator_condition: false,
  station1_sideSlipIndicator2_condition: false,
  station1_mgbEngineOilCooler_condition: false,
  station2_frontDoorJettison_condition: false,
  station2_leftCabinAccess_condition: false,
  station2_landingGear_condition: false,
  station2_staticPressure_condition: false,
  station2_oatProbe_condition: false,
  station2_antennas_condition: false,
  station2_lights_condition: false,
  station2_lowerCowlings_condition: false,
  station2_leftCargoDoorOpen_opening: false,
  station2_leftCargoDoorClosed_closed: false,
  station2_fuelTank_condition: false,
  station2_rearCargoDoorOpen_opening: false,
  station2_rearCargoBay_harness: false,
  station2_elt_condition: false,
  station2_rearCargoDoorClosed_closed: false,
  station2_mgbCowlings_opening: false,
  station2_upperCowling_security: false,
  station2_mgb_condition: false,
  station2_transmissionDeck_cleanliness: false,
  station2_mgbSupportBars_condition: false,
  station2_hydraulicSystem_condition: false,
  station2_servos_security: false,
  station2_coolingFan_condition: false,
  station2_gimbalRing_fitting: false,
  station2_electricalHarnesses_condition: false,
  station2_fuelShutoff_condition: false,
  station2_mgbCowlingLH_safety: false,
  engine_airInlet_condition: false,
  engine_firewall_condition: false,
  engine_accessories_condition: false,
  engine_transmissionDeck_condition: false,
  engine_case_condition: false,
  engine_oilFilter_condition: false,
  engine_fuelFilter_condition: false,
  engine_oilSystem_condition: false,
  engine_mounts_condition: false,
  engine_deckDrainHoles_condition: false,
  engine_exhaustPipe_condition: false,
  station3_scissors_condition: false,
  station3_swashPlate_condition: false,
  station3_pitchChangeRods_condition: false,
  station3_rotorShaft_condition: false,
  mainRotor_head_condition: false,
  mainRotor_starflex_condition: false,
  mainRotor_starRecesses_condition: false,
  mainRotor_sphericalBearings_condition: false,
  mainRotor_ballJoints_condition: false,
  mainRotor_starArms_condition: false,
  mainRotor_vibrationAbsorber_condition: false,
  mainRotor_blades_condition: false,
  mainRotor_rightCargoDoor_opening: false,
  mainRotor_rightCargoDoor_closed: false,
  mainRotor_gpuPlug_condition: false,
  mainRotor_rhMgbCowling_opening: false,
  mainRotor_transmissionDeck_cleanliness: false,
  mainRotor_mgbSupportBars_condition: false,
  mainRotor_oilCooler_condition: false,
  mainRotor_servos_security: false,
  mainRotor_hydraulicSystem_condition: false,
  mainRotor_hydraulicTank_condition: false,
  mainRotor_engineOilTank_condition: false,
  mainRotor_electricalHarnesses_condition: false,
  mainRotor_gimbalRing_fitting: false,
  mainRotor_rhSideMgbCowling_closed: false,
  mainRotor_landingGear_condition: false,
  mainRotor_lowerFairings_closed: false,
  mainRotor_rhCabinAccess_condition: false,
  mainRotor_frontDoorJettison_condition: false,
  cabin_general_cleanliness: false,
  cabin_seats_condition: false,
  cabin_doorJettison_checked: false,
  cabin_fireExtinguisher_condition: false,
  cabin_circuitBreakers_set: false,
  cabin_scu_position: false,
  cabin_batterySwitchOn_on: false,
  cabin_vemd_flightReport: false,
  cabin_vemd_flightTimes: false,
  cabin_vemd_cycles: false,
  cabin_vemd_advisoryMessages: false,
  cabin_vemd_recordData: false,
  cabin_batterySwitchOff_off: false,
});

export const areAllPostInspectionChecksComplete = (formData = {}) =>
  Object.entries(formData)
    .filter(([, value]) => typeof value === "boolean")
    .every(([, value]) => value === true);
