export const rawData = [
  // Row 6 - AIRWORTHINESS CERTIFICATE
  {
    _id: "6",
    rowType: "part",
    componentName: "AIRWORTHINESS CERTIFICATE",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "365",
    dayType: "D",
    dateCW: "2025-04-02",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 7 - REGISTRATION CERTIFICATE
  {
    _id: "7",
    rowType: "part",
    componentName: "REGISTRATION CERTIFICATE",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "365",
    dayType: "D",
    dateCW: "2027-12-16",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 8 - RADIO LICENSE
  {
    _id: "8",
    rowType: "part",
    componentName: "RADIO LICENSE",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "365",
    dayType: "D",
    dateCW: "2024-12-17",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 9 - WEIGHT & BALANCE
  {
    _id: "9",
    rowType: "part",
    componentName: "WEIGHT & BALANCE",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "1825",
    dayType: "D",
    dateCW: "2025-12-18",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 10 - FIRST AID KIT
  {
    _id: "10",
    rowType: "part",
    componentName: "FIRST AID KIT PN:8095X900 SN:M2X-P4-6S",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "730",
    dayType: "D",
    dateCW: "2026-12-19",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 11 - HAND FIRE EXTINGUISHER
  {
    _id: "11",
    rowType: "part",
    componentName: "HAND FIRE EXTINGUISHER BOTTLE PN:S262A10T1001 SN:ACW04950",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "3650",
    dayType: "D",
    dateCW: "2026-12-20",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 12 - TRANSPONDER CHECK
  {
    _id: "12",
    rowType: "part",
    componentName: "TRANSPONDER CHECK",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "365",
    dayType: "D",
    dateCW: "2027-03-17",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 13 - ELT check
  {
    _id: "13",
    rowType: "part",
    componentName: "ELT check",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "365",
    dayType: "D",
    dateCW: "2027-03-17",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 14 - ELT BATTERY
  {
    _id: "14",
    rowType: "part",
    componentName: "ELT BATTERY PN:704A45737078 SN:LX1101340789",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "2190",
    dayType: "D",
    dateCW: "2027-03-17",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 15 - PITOT static check
  {
    _id: "15",
    rowType: "part",
    componentName: "PITOT static check",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "730",
    dayType: "D",
    dateCW: "2027-03-27",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 18 - NEXT 10 HRS. INSPECTION (skipping row 16-17 as blank/headers)
  {
    _id: "18",
    rowType: "part",
    componentName: "NEXT 10 HRS. INSPECTION",
    hourLimit1: "10",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "D",
    dateCW: "2022-12-05",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "433.4",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 19 - NEXT 150 HRS. INSPECTION
  {
    _id: "19",
    rowType: "part",
    componentName: "NEXT 150 HRS. INSPECTION",
    hourLimit1: "150",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "D",
    dateCW: "2022-12-05",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "283.4",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 20 - 150 HRS / 12 M
  {
    _id: "20",
    rowType: "part",
    componentName: "150 HRS / 12 M",
    hourLimit1: "150",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "365",
    dayType: "D",
    dateCW: "2026-12-04",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "283.4",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 21 - 12M INSPECTION
  {
    _id: "21",
    rowType: "part",
    componentName: "12M INSPECTION",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "365",
    dayType: "D",
    dateCW: "2026-12-05",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 22 - HMU
  {
    _id: "22",
    rowType: "part",
    componentName: "HMU(PUMP AND METERING VALVE ADJ.ASSY PN:0292862200 SN:",
    hourLimit1: "4000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "365",
    dayType: "D",
    dateCW: "2024-12-06",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 23 - 600HRS
  {
    _id: "23",
    rowType: "part",
    componentName: "600HRS",
    hourLimit1: "600",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2024-12-07",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "2025-12-30",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 24 - 600HRS / 24M
  {
    _id: "24",
    rowType: "part",
    componentName: "600HRS / 24M",
    hourLimit1: "600",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "730",
    dayType: "D",
    dateCW: "2024-12-08",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "2025-01-22",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 25 - 1200HRS
  {
    _id: "25",
    rowType: "part",
    componentName: "1200HRS",
    hourLimit1: "1200",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "1460",
    dayType: "",
    dateCW: "2024-12-09",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "2025-12-17",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 26 - 1200HRS / 48M
  {
    _id: "26",
    rowType: "part",
    componentName: "1200HRS / 48M",
    hourLimit1: "1200",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "1460",
    dayType: "D",
    dateCW: "2024-12-10",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "2025-12-18",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 27 - 5000HRS / 144M
  {
    _id: "27",
    rowType: "part",
    componentName: "5000HRS / 144M",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "4380",
    dayType: "D",
    dateCW: "2026-12-11",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "2027-12-19",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 28 - Engine Fuel Filter
  {
    _id: "28",
    rowType: "part",
    componentName: "Engine Fuel Filter P/N:",
    hourLimit1: "600",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "D",
    dateCW: "2026-12-12",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "524.5",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 29 - Engine Oil Filter
  {
    _id: "29",
    rowType: "part",
    componentName: "Engine Oil Filter P/N:",
    hourLimit1: "800",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "D",
    dateCW: "2024-12-13",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "123.45",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 30 - MGB Oil Filter
  {
    _id: "30",
    rowType: "part",
    componentName: "MGB Oil Filter P/N:",
    hourLimit1: "600",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "730",
    dayType: "D",
    dateCW: "2026-12-14",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "314.6",
    dateDue: "2027-12-17",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "( Margin 73D)",
  },
  // Row 31 - Hydraulic Filter
  {
    _id: "31",
    rowType: "part",
    componentName: "Hydraulic Filter P/N:",
    hourLimit1: "2500",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "1460",
    dayType: "D",
    dateCW: "2024-12-15",
    hoursCW: "775",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "2025-12-17",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 32 - HYDRAULIC FLUID CHANGE
  {
    _id: "32",
    rowType: "part",
    componentName: "HYDRAULIC FLUID CHANGE",
    hourLimit1: "",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "D",
    dateCW: "2024-12-16",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "( Margin 73D)",
  },
  // Row 33 - SLING
  {
    _id: "33",
    rowType: "part",
    componentName: "SLING",
    hourLimit1: "",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "365",
    dayType: "D",
    dateCW: "2024-12-17",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "2025-12-17",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 34 - TRDS BEARING
  {
    _id: "34",
    rowType: "part",
    componentName: "TRDS BEARING PN: (60 MONTHS)",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "1825",
    dayType: "D",
    dateCW: "2026-12-18",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "2027-12-17",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 35 - HYD PUMP Drive Brg.
  {
    _id: "35",
    rowType: "part",
    componentName: "HYD PUMP Drive Brg. P/N: (72 MONTHS)",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "2190",
    dayType: "D",
    dateCW: "2024-12-19",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "2026-12-17",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 36 - ENGINE BORESCOPE INSP.
  {
    _id: "36",
    rowType: "part",
    componentName: "ENGINE BORESCOPE INSP.",
    hourLimit1: "800",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "D",
    dateCW: "2024-12-20",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "800",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 37 - AIRFRAME COMPONENT (Header)
  {
    _id: "37",
    rowType: "header",
    componentName: "AIRFRAME COMPONENT",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 38 - Electrical Power System (Header)
  {
    _id: "38",
    rowType: "header",
    componentName: "Electrical Power System",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 39 - Saft Battery
  {
    _id: "39",
    rowType: "part",
    componentName: "Saft Battery (Ni-Cad) PN:151CH1 SN:202002875",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "OC",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 40 - Saft Battery Top Charge
  {
    _id: "40",
    rowType: "part",
    componentName: "Saft Battery (Ni-Cad) PN:151CH1 SN:202002875   Top Charge",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "91",
    dayType: "D",
    dateCW: "2020-09-02",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "2025-12-18",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 41 - Fire Protection (Header)
  {
    _id: "41",
    rowType: "header",
    componentName: "Fire Protection",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 42 - Cabin Fire Extinguisher
  {
    _id: "42",
    rowType: "part",
    componentName: "Cabin Fire Extinguisher PN:S26A10T1001 SN:ACW04964",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "3650",
    dayType: "D",
    dateCW: "2020-08-18",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 43 - Cabin Fire Extinguisher Re-weigh
  {
    _id: "43",
    rowType: "part",
    componentName: "Cabin Fire Extinguisher Re-weigh",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "30",
    dayType: "",
    dateCW: "2021-11-18",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "2025-12-18",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 44 - Floats of Emergency Flotation System (Header)
  {
    _id: "44",
    rowType: "header",
    componentName: "Floats of Emergency Flotation System",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 45 - Emergency Floats (LH)
  {
    _id: "45",
    rowType: "part",
    componentName: "Emergency Floats (LH) MPN:200733-0 SN:3330",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "3650",
    dayType: "D",
    dateCW: "2020-11-01",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 46 - Emergency Floats (RH)
  {
    _id: "46",
    rowType: "part",
    componentName: "Emergency Floats (RH) MPN:200734-0 SN:3337",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "3650",
    dayType: "D",
    dateCW: "2020-11-01",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 47 - Emergency Floats Gear CYLINDER ASSY SN:5440
  {
    _id: "47",
    rowType: "part",
    componentName:
      "Emergency Floats Gear CYLINDER ASSY PN:704A42693012 SN:5440",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "5475",
    dayType: "D",
    dateCW: "2020-07-29",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 48 - Emergency Floats Gear CYLINDER ASSY SN:5436
  {
    _id: "48",
    rowType: "part",
    componentName:
      "Emergency Floats Gear CYLINDER ASSY PN:704A42693012 SN:5436",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "5475",
    dayType: "D",
    dateCW: "2020-07-29",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 49 - Hydrotest Floats Gear Cylinder SN:5485
  {
    _id: "49",
    rowType: "part",
    componentName: "Hydrotest Floats Gear Cylinder 200740-2 SN:5485",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "1825",
    dayType: "D",
    dateCW: "2022-07-29",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 50 - Hydrotest Floats Gear Cylinder SN:5441
  {
    _id: "50",
    rowType: "part",
    componentName: "Hydrotest Floats Gear Cylinder PN:200740-2 SN:5441",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "1825",
    dayType: "D",
    dateCW: "2022-07-30",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 51 - Onboard Systems TSI
  {
    _id: "51",
    rowType: "part",
    componentName: "Onboard Systems PN: SN: TSI:",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "1825",
    dayType: "D",
    dateCW: "2020-07-31",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 52 - Onboard Systems
  {
    _id: "52",
    rowType: "part",
    componentName: "Onboard Systems PN: SN:",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "3650",
    dayType: "D",
    dateCW: "2020-08-01",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 53 - Main Rotor Blade (Header)
  {
    _id: "53",
    rowType: "header",
    componentName: "Main Rotor Blade",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 54 - Main Rotor Blade RED
  {
    _id: "54",
    rowType: "part",
    componentName: "Main Rotor Blade PN:355A11-0030-04 SN:32837 RED",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 55 - Main Rotor Blade BLUE
  {
    _id: "55",
    rowType: "part",
    componentName: "Main Rotor Blade PN:355A11-0030-04 SN:32848 BLUE",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 56 - Main Rotor Blade YELLOW
  {
    _id: "56",
    rowType: "part",
    componentName: "Main Rotor Blade PN:355A11-0030-04 SN:32845 YELLOW",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 57 - Poly-Urethane Tape (MRB) (Header)
  {
    _id: "57",
    rowType: "header",
    componentName: "Poly-Urethane Tape (MRB)",
    hourLimit1: "OC",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 58 - Main Rotor HUB (Header)
  {
    _id: "58",
    rowType: "header",
    componentName: "Main Rotor HUB PN:355A31000202 SN:M5815",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 59 - Thrust Bearing Spherical LK27068
  {
    _id: "59",
    rowType: "part",
    componentName: "Thrust Bearing Spherical PN:704A33633208 SN:LK27068",
    hourLimit1: "6400",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 60 - Thrust Bearing Spherical LK27071
  {
    _id: "60",
    rowType: "part",
    componentName: "Thrust Bearing Spherical PN:704A33633208 SN:LK27071",
    hourLimit1: "6400",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 61 - Thrust Bearing Spherical LK27082
  {
    _id: "61",
    rowType: "part",
    componentName: "Thrust Bearing Spherical PN:704A33633208 SN:LK27082",
    hourLimit1: "6400",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 62 - Starflex Main Blade Pin MHR M9280
  {
    _id: "62",
    rowType: "part",
    componentName: "Starflex Main Blade Pin MHR PN:350A31-3020-20 SN:M9280",
    hourLimit1: "12000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 63 - Starflex Main Blade Pin MHR M9291
  {
    _id: "63",
    rowType: "part",
    componentName: "Starflex Main Blade Pin MHR PN:350A31-3020-20 SN:M9291",
    hourLimit1: "12000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 64 - Starflex Main Blade Pin MHR M9300
  {
    _id: "64",
    rowType: "part",
    componentName: "Starflex Main Blade Pin MHR PN:350A31-3020-20 SN:M9300",
    hourLimit1: "12000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 65 - Starflex Main Blade Pin MHR M9665
  {
    _id: "65",
    rowType: "part",
    componentName: "Starflex Main Blade Pin MHR PN:350A31-3020-20 SN:M9665",
    hourLimit1: "12000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 66 - Starflex Main Blade Pin MHR M9693
  {
    _id: "66",
    rowType: "part",
    componentName: "Starflex Main Blade Pin MHR PN:350A31-3020-20 SN:M9693",
    hourLimit1: "12000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 67 - Starflex Main Blade Pin MHR M9695
  {
    _id: "67",
    rowType: "part",
    componentName: "Starflex Main Blade Pin MHR PN:350A31-3020-20 SN:M9695",
    hourLimit1: "12000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 68 - Horn, Pitch MAP14067
  {
    _id: "68",
    rowType: "part",
    componentName: "Horn, Pitch PN:350A31-1877-03 SN:MAP14067",
    hourLimit1: "80000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 69 - Horn, Pitch MAP14070
  {
    _id: "69",
    rowType: "part",
    componentName: "Horn, Pitch PN:350A31-1877-03 SN:MAP14070",
    hourLimit1: "80000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 70 - Horn, Pitch MAP14011
  {
    _id: "70",
    rowType: "part",
    componentName: "Horn, Pitch PN:350A31-1877-03 SN:MAP14011",
    hourLimit1: "80000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 71 - Flange,Sleeve Lower M51875
  {
    _id: "71",
    rowType: "part",
    componentName: "Flange,Sleeve Lower PN:350A31-1850-02 SN:M51875",
    hourLimit1: "6600",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 72 - Flange,Sleeve Lower M52016
  {
    _id: "72",
    rowType: "part",
    componentName: "Flange,Sleeve Lower PN:350A31-1850-02 SN:M52016",
    hourLimit1: "6600",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 73 - Flange,Sleeve Lower M52020
  {
    _id: "73",
    rowType: "part",
    componentName: "Flange,Sleeve Lower PN:350A31-1850-02 SN:M52020",
    hourLimit1: "6600",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 74 - Flange,Sleeve Upper M51899
  {
    _id: "74",
    rowType: "part",
    componentName: "Flange,Sleeve Upper PN:350A31-1850-03 SN:M51899",
    hourLimit1: "6600",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 75 - Flange,Sleeve Upper M51932
  {
    _id: "75",
    rowType: "part",
    componentName: "Flange,Sleeve Upper PN:350A31-1850-03 SN:M51932",
    hourLimit1: "6600",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 76 - Flange,Sleeve Upper M51945
  {
    _id: "76",
    rowType: "part",
    componentName: "Flange,Sleeve Upper PN:350A31-1850-03 SN:M51945",
    hourLimit1: "6600",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 77 - Spherical Thrust Bearing Bolt 86093
  {
    _id: "77",
    rowType: "part",
    componentName:
      "Spherical Thrust Bearing Bolt (SCREW) PN:350A31-1854-21 SN:86093",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 78 - Spherical Thrust Bearing Bolt 86094
  {
    _id: "78",
    rowType: "part",
    componentName:
      "Spherical Thrust Bearing Bolt (SCREW) PN:350A31-1854-21 SN:86094",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 79 - Spherical Thrust Bearing Bolt 86098
  {
    _id: "79",
    rowType: "part",
    componentName:
      "Spherical Thrust Bearing Bolt (SCREW) PN:350A31-1854-21 SN:86098",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 80 - Spherical Thrust Bearing Bolt 86099
  {
    _id: "80",
    rowType: "part",
    componentName:
      "Spherical Thrust Bearing Bolt (SCREW) PN:350A31-1854-21 SN:86099",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 81 - Spherical Thrust Bearing Bolt 86100
  {
    _id: "81",
    rowType: "part",
    componentName:
      "Spherical Thrust Bearing Bolt (SCREW) PN:350A31-1854-21 SN:86100",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 82 - Spherical Thrust Bearing Bolt 86102
  {
    _id: "82",
    rowType: "part",
    componentName:
      "Spherical Thrust Bearing Bolt (SCREW) PN:350A31-1854-21 SN:86102",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 83 - StarFlex STAR 26 FLODS M42
  {
    _id: "83",
    rowType: "part",
    componentName: "(StarFlex STAR 26 FLODS M42)PN:350A31-1918-00 SR:M8079",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 84 - Main Rotor Shaft PN (Header)
  {
    _id: "84",
    rowType: "header",
    componentName: "Main Rotor Shaft PN:355A37-0006-01M SN:M2058",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 85 - Shaft,Main Rotor
  {
    _id: "85",
    rowType: "part",
    componentName: "Shaft,Main Rotor PN:350A37-1290-04 SN:FR3518",
    hourLimit1: "90000",
    hourLimit2: "TC",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 86 - Swashplate
  {
    _id: "86",
    rowType: "part",
    componentName: "Swashplate (Bearing EXTERNAL) PN:704A33653110 SN:NR8131",
    hourLimit1: "4800",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 87 - LINK, SCISSORS SD8195
  {
    _id: "87",
    rowType: "part",
    componentName: "LINK, SCISSORS PN:350A37-1127-02 SN:SD8195",
    hourLimit1: "3000",
    hourLimit2: "INF",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 88 - LINK, SCISSORS SD8450
  {
    _id: "88",
    rowType: "part",
    componentName: "LINK, SCISSORS PN:350A37-1127-02 SN:SD8450",
    hourLimit1: "3000",
    hourLimit2: "INF",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 89 - CONNECT COMPASS HIGHER EQUIPPED SD2635
  {
    _id: "89",
    rowType: "part",
    componentName:
      "CONNECT COMPASS HIGHER EQUIPPED PN:350A37-1126-03 SN:SD2635",
    hourLimit1: "3000",
    hourLimit2: "INF",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 90 - CONNECT COMPASS HIGHER EQUIPPED SD6581
  {
    _id: "90",
    rowType: "part",
    componentName:
      "CONNECT COMPASS HIGHER EQUIPPED PN:350A37-1126-03 SN:SD6581",
    hourLimit1: "3000",
    hourLimit2: "INF",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 91 - HOUSING,LOWER,ROTOR MAST
  {
    _id: "91",
    rowType: "part",
    componentName: "HOUSING,LOWER,ROTOR MAST PN:350A37-1292-00 SN:S4922",
    hourLimit1: "3000",
    hourLimit2: "INF",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 92 - CASING,UPPER,MAIN ROTOR SHAFT
  {
    _id: "92",
    rowType: "part",
    componentName: "CASING,UPPER,MAIN ROTOR SHAFT PN:350A37-1291-00 SN:S4802",
    hourLimit1: "3000",
    hourLimit2: "INF",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 93 - DISK ASSY ROTATING SCISSORS
  {
    _id: "93",
    rowType: "part",
    componentName: "DISK ASSY ROTATING SCISSORS PN:355A37-1235-27 SN:S1573",
    hourLimit1: "20000",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 94 - STAR ASSY NO-ROTATING
  {
    _id: "94",
    rowType: "part",
    componentName: "STAR ASSY NO-ROTATING PN:350A37-1002-07 SN:CUR03317",
    hourLimit1: "3000",
    hourLimit2: "INF",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 95 - ROTATING SWAHERPLATE
  {
    _id: "95",
    rowType: "part",
    componentName: "ROTATING SWAHERPLATE PN:350A37-1018-00 SN:CUR00899",
    hourLimit1: "20000",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 96 - BEARING, 4 CONTACTS
  {
    _id: "96",
    rowType: "part",
    componentName: "BEARING, 4 CONTACTS PN:704A33651158",
    hourLimit1: "6300",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 97-108 - MRH Attachment Bolt (12 rows)
  {
    _id: "97",
    rowType: "part",
    componentName: "MRH Attachment Bolt (SCREW) PN:350A37-1245-20 SN:120952",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  {
    _id: "98",
    rowType: "part",
    componentName: "MRH Attachment Bolt (SCREW) PN:350A37-1245-20 SN:120952",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  {
    _id: "99",
    rowType: "part",
    componentName: "MRH Attachment Bolt (SCREW) PN:350A37-1245-20 SN:121091",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  {
    _id: "100",
    rowType: "part",
    componentName: "MRH Attachment Bolt (SCREW) PN:350A37-1245-20 SN:121099",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  {
    _id: "101",
    rowType: "part",
    componentName: "MRH Attachment Bolt (SCREW)PN:350A37-1245-20 SN:121101",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  {
    _id: "102",
    rowType: "part",
    componentName: "MRH Attachment Bolt (SCREW) PN:350A37-1245-20 SN:121465",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  {
    _id: "103",
    rowType: "part",
    componentName: "MRH Attachment Bolt (SCREW) PN:350A37-1245-20 SN:133604",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  {
    _id: "104",
    rowType: "part",
    componentName: "MRH Attachment Bolt (SCREW) PN:350A37-1245-20 SN:133607",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  {
    _id: "105",
    rowType: "part",
    componentName: "MRH Attachment Bolt (SCREW) PN:350A37-1245-20 SN:133678",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  {
    _id: "106",
    rowType: "part",
    componentName: "MRH Attachment Bolt (SCREW) PN:350A37-1245-20 SN:133679",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  {
    _id: "107",
    rowType: "part",
    componentName: "MRH Attachment Bolt (SCREW) PN:350A37-1245-20 SN:133683",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  {
    _id: "108",
    rowType: "part",
    componentName: "MRH Attachment Bolt (SCREW) PN:350A37-1245-20 SN:133684",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 109 - Main Gear Box TBO (Header)
  {
    _id: "109",
    rowType: "header",
    componentName: "Main Gear Box TBO",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 110 - FUEL PUMP (Header)
  {
    _id: "110",
    rowType: "header",
    componentName: "FUEL PUMP",
    hourLimit1: "",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 111 - TRANSMISSION OIL CHANGE (Header)
  {
    _id: "111",
    rowType: "header",
    componentName: "TRANSMISSION OIL CHANGE",
    hourLimit1: "",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 112 - Epicyclic Reduction Gear
  {
    _id: "112",
    rowType: "part",
    componentName: "Epicyclic Reduction Gear PN:350A32-0120-01 SN:M10337",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-29",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 113 - Conic Pinion
  {
    _id: "113",
    rowType: "part",
    componentName: "Conic Pinion (FIXED RING LLI) PN:350A32-1119-20 SN:L10349",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 114 - PLANET GEAR, NITRIDED
  {
    _id: "114",
    rowType: "part",
    componentName: "(PLANET GEAR, NITRIDED) PN:350A32-1075-20 SN:L11662",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 115 - MOUNT,Planet Gear
  {
    _id: "115",
    rowType: "part",
    componentName: "MOUNT,Planet Gear,4 CONTACTS PN:350A32-1089-21 SN:L7912",
    hourLimit1: "49000",
    hourLimit2: "TC",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 116 - Planet Gear Assy M11253
  {
    _id: "116",
    rowType: "part",
    componentName: "Planet Gear Assy PN:350A32-1114-00 SN:M11253",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "19819.9",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "20000",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 117 - Planet Gear Assy M11265
  {
    _id: "117",
    rowType: "part",
    componentName: "Planet Gear Assy PN:350A32-1114-00 SN:M11265",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 118 - Planet Gear Assy M11270
  {
    _id: "118",
    rowType: "part",
    componentName: "Planet Gear Assy PN:350A32-1114-00 SN:M11270",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 119 - Planet Gear Assy M11283
  {
    _id: "119",
    rowType: "part",
    componentName: "Planet Gear Assy PN:350A32-1114-00 SN:M11283",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 120 - Planet Gear Assy M11285
  {
    _id: "120",
    rowType: "part",
    componentName: "Planet Gear Assy PN:350A32-1114-00 SN:M11285",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 122 - Oil Pump Assy
  {
    _id: "122",
    rowType: "part",
    componentName: "Oil Pump Assy. PN:350A32-0400-00 SN:M6733",
    hourLimit1: "3500",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-16",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 124 - REDUCTION GEAR TAPERED ASSY
  {
    _id: "124",
    rowType: "part",
    componentName: "REDUCTION GEAR TAPERED ASSY PN:350A32-0350-02 SN:M6462",
    hourLimit1: "3000",
    hourLimit2: "FH",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 125 - REDUCTION GEAR TAPERED ASSY (2nd)
  {
    _id: "125",
    rowType: "part",
    componentName: "REDUCTION GEAR TAPERED ASSY PN:350A32-0350-02 SN:M6463",
    hourLimit1: "8760",
    hourLimit2: "D",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 126 - MGB BOTTOM Casing
  {
    _id: "126",
    rowType: "part",
    componentName: "MGB BOTTOM Casing ASSY,LOWER PN:350A32-3119-05 SN:MAP10581",
    hourLimit1: "20000",
    hourLimit2: "FH",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 127 - MAIN HOUSING DOUBLE HYD
  {
    _id: "127",
    rowType: "part",
    componentName: "MAIN HOUSING DOUBLE HYD PN:350A32-3191-00 SN:MAP575",
    hourLimit1: "89800",
    hourLimit2: "TC",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 128 - BEVEL GEAR
  {
    _id: "128",
    rowType: "part",
    componentName: "BEVEL GEAR PN:350A32-3173-20 SN:L6505",
    hourLimit1: "20000",
    hourLimit2: "FH",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 129 - BEVEL WHEEL
  {
    _id: "129",
    rowType: "part",
    componentName: "BEVEL WHEEL PN:350A32-3166-20 SN:L5587",
    hourLimit1: "20000",
    hourLimit2: "FH",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-08",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 130 - Tail Rotor Blades (Header)
  {
    _id: "130",
    rowType: "header",
    componentName: "Tail Rotor Blades",
    hourLimit1: "",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 131 - Tail Rotor Blade
  {
    _id: "131",
    rowType: "part",
    componentName: "Tail Rotor Blade PN:355A12-0060-04 SN:24550",
    hourLimit1: "4000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-07",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 132 - Poly-Urethane Tapes (Header)
  {
    _id: "132",
    rowType: "header",
    componentName: "Poly-Urethane Tapes",
    hourLimit1: "OC",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 133 - HANGER BEARING (Header)
  {
    _id: "133",
    rowType: "header",
    componentName: "HANGER BEARING",
    hourLimit1: "",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 134 - SPLIT BUSHING (Header)
  {
    _id: "134",
    rowType: "header",
    componentName: "SPLIT BUSHING",
    hourLimit1: "",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 135 - Tail Rotor Gear Box (Header)
  {
    _id: "135",
    rowType: "header",
    componentName: "Tail Rotor Gear Box",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 136 - TAIL GEARBOX OIL CHANGE (Header)
  {
    _id: "136",
    rowType: "header",
    componentName: "TAIL GEARBOX OIL CHANGE",
    hourLimit1: "",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 137 - Tail Rotor Gear Box PN
  {
    _id: "137",
    rowType: "part",
    componentName: "Tail Rotor Gear Box PN:350A33-0210-00 SN:MA121434",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-04",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 138 - Pitch Change
  {
    _id: "138",
    rowType: "part",
    componentName:
      "Pitch Change(LEVER T.G.B. CONTROL) PN:350A33-1535.00 SN:MA88205",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-04",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 139 - Bevel Wheel
  {
    _id: "139",
    rowType: "part",
    componentName: "Bevel Wheel PN:350A33-1001-21 SN:L13945",
    hourLimit1: "16500",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-04",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 140 - Bevel Gear
  {
    _id: "140",
    rowType: "part",
    componentName: "Bevel Gear PN:350A33-1000-21 SN:L15917",
    hourLimit1: "5500",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-04",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 141 - T.G.B Casing
  {
    _id: "141",
    rowType: "part",
    componentName: "T.G.B Casing PN:350A33-1090-02 SN:MA119293",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-04",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 142 - Tail Rotor Shaft
  {
    _id: "142",
    rowType: "part",
    componentName: "Tail Rotor Shaft PN:350A33-1092-01 SN:MA119042",
    hourLimit1: "20000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-04",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 143 - Spider (Header)
  {
    _id: "143",
    rowType: "header",
    componentName: "Spider PN:350A33-2167-01 SN:MA121434",
    hourLimit1: "",
    hourLimit2: "OC",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-07-04",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 144 - Spider Greasable Bearing
  {
    _id: "144",
    rowType: "part",
    componentName: "Spider Greasable Bearing PN:704A33651210 SN:NR11205",
    hourLimit1: "3000",
    hourLimit2: "FH",
    hourLimit3: "",
    dayLimit: "1825",
    dayType: "D",
    dateCW: "2022-07-04",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 145 - ELASTOMERIC Pitch Rod LK6660
  {
    _id: "145",
    rowType: "part",
    componentName: "ELASTOMERIC Pitch Rod PN:LB6-1231-3-2 SN:LK6660",
    hourLimit1: "20000",
    hourLimit2: "FH",
    hourLimit3: "",
    dayLimit: "1825",
    dayType: "D",
    dateCW: "2022-07-05",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 146 - ELASTOMERIC Pitch Rod LK6670
  {
    _id: "146",
    rowType: "part",
    componentName: "ELASTOMERIC Pitch Rod PN:LB6-1231-3-2 SN:LK6670",
    hourLimit1: "20000",
    hourLimit2: "FH",
    hourLimit3: "",
    dayLimit: "1825",
    dayType: "D",
    dateCW: "2022-07-06",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 147 - Tail rotor drive shaft - Greasable bearing
  {
    _id: "147",
    rowType: "part",
    componentName: "Tail rotor drive shaft - Greasable bearing",
    hourLimit1: "3600",
    hourLimit2: "FH",
    hourLimit3: "",
    dayLimit: "1825",
    dayType: "D",
    dateCW: "2022-07-07",
    hoursCW: "0",
    daysRemaining: "3600",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 150 - TAIL SERVO
  {
    _id: "150",
    rowType: "part",
    componentName: "TAIL SERVO PN:704A44831142 SN:SC5072",
    hourLimit1: "3000",
    hourLimit2: "FH",
    hourLimit3: "",
    dayLimit: "7300",
    dayType: "D",
    dateCW: "2020-06-29",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 152 - Servo-Control Front and LH
  {
    _id: "152",
    rowType: "part",
    componentName: "Servo-Control Front and LH PN:704A44831102 SN:SC8042",
    hourLimit1: "3000",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "7300",
    dayType: "D",
    dateCW: "2020-07-01",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 154 - MR (Servo-Control,FRONT AND LH) SN:4283
  {
    _id: "154",
    rowType: "part",
    componentName: "MR (Servo-Control,FRONT AND LH) PN:SC8042 SN:4283",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "7300",
    dayType: "D",
    dateCW: "",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 155 - MR (Servo Control,FRONT AND LH) SN:4286
  {
    _id: "155",
    rowType: "part",
    componentName: "MR (Servo Control,FRONT AND LH) PN:SC8042 SN:4286",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "7300",
    dayType: "D",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 156 - MR (Servo Control,FRONT AND RH) SN:2265
  {
    _id: "156",
    rowType: "part",
    componentName: "MR (Servo Control,FRONT AND RH) PN:SC8043 SN:2265",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "7300",
    dayType: "D",
    dateCW: "2020-07-09",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 157 - (TR) Rear (ServoControl,TAIL) SN:4445
  {
    _id: "157",
    rowType: "part",
    componentName: "(TR) Rear (ServoControl,TAIL) PN:SC5072 SN:4445",
    hourLimit1: "3000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "7300",
    dayType: "D",
    dateCW: "2020-07-04",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 158 - Suspension (BAR,FWD,MGB) SN:7957
  {
    _id: "158",
    rowType: "part",
    componentName: "Suspension (BAR,FWD,MGB) PN:704A33633226 SN:7957",
    hourLimit1: "3600",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "2190",
    dayType: "",
    dateCW: "2020-07-22",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 159 - Suspension (BAR,FWD,MGB) SN:7939
  {
    _id: "159",
    rowType: "part",
    componentName: "Suspension (BAR,FWD,MGB) PN:704A33633226 SN:7939",
    hourLimit1: "3600",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "2190",
    dayType: "",
    dateCW: "2020-07-23",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 160 - Starting (Header)
  {
    _id: "160",
    rowType: "header",
    componentName: "Starting",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 161 - Starter Generator
  {
    _id: "161",
    rowType: "part",
    componentName: "Starter Generator PN:704A46101026 SN:S01106",
    hourLimit1: "1200",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-02-27",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 162 - Starter Generator brushes
  {
    _id: "162",
    rowType: "part",
    componentName:
      "Starter Generator PN:704A46101026 SN:S01106 Cheking of brushes 300h",
    hourLimit1: "300",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2023-02-27",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 163 - Hydraulic Pump Drive Brg.
  {
    _id: "163",
    rowType: "part",
    componentName: "Hydraulic Pump Drive Brg. P/N:704A34310004 SN:190722964",
    hourLimit1: "3600",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "2190",
    dayType: "D",
    dateCW: "2020-07-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 164 - Poly V Belt
  {
    _id: "164",
    rowType: "part",
    componentName: "Poly V Belt P/N:POLYV597K4 SN:F3444 POLY-V",
    hourLimit1: "3600",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "2190",
    dayType: "D",
    dateCW: "2020-07-21",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 165 - POWERPLANT COMPONENT/ ENGINE (Header)
  {
    _id: "165",
    rowType: "header",
    componentName: "POWERPLANT COMPONENT/ ENGINE",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 166 - Engine Model (Header)
  {
    _id: "166",
    rowType: "header",
    componentName: "Engine Model: Arriel 2D",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 167 - Engine S/N (Header)
  {
    _id: "167",
    rowType: "header",
    componentName: "Engine S/N: 50014",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 168 - ENGINE OIL CHANGE (Header)
  {
    _id: "168",
    rowType: "header",
    componentName: "ENGINE OIL CHANGE",
    hourLimit1: "",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "D",
    dateCW: "2020-06-10",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 169 - Powerplant
  {
    _id: "169",
    rowType: "part",
    componentName: "Powerplant (Turbomeca Arriel 2D) SN:50307",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "5475",
    dayType: "D",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 170 - Module 01
  {
    _id: "170",
    rowType: "part",
    componentName: "Module 01- Accessory Gear Box PN:70BM010020 SN:23586",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "5475",
    dayType: "D",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 171 - Module 02
  {
    _id: "171",
    rowType: "part",
    componentName: "Module 02- Axial Compressor PN:70BM020010 SN:26358",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "5475",
    dayType: "D",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 172 - Module 03
  {
    _id: "172",
    rowType: "part",
    componentName: "Module 03- Gas Generator PN:70BM030070 SN:33923",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "5475",
    dayType: "D",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 173 - Module 04
  {
    _id: "173",
    rowType: "part",
    componentName: "Module 04- Free Turbine PN:70BM040020 SN:29363",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "5475",
    dayType: "D",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 174 - Module 05
  {
    _id: "174",
    rowType: "part",
    componentName: "Module 05- Reduction Gear PN:70BM050010 SN:27354",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "5475",
    dayType: "D",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 175 - Module 02 TBO 4000Hrs
  {
    _id: "175",
    rowType: "part",
    componentName: "Module 02 TBO 4000Hrs",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "5475",
    dayType: "D",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 176 - Axial Compressor Wheel (Header)
  {
    _id: "176",
    rowType: "header",
    componentName: "Axial Compressor Wheel PN:2292153370 SN:4357FB",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 177 - N1 line
  {
    _id: "177",
    rowType: "header",
    componentName: "N1 22000 C LIFE LIMIT",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 178 - Module 03 Life Limited Parts (Header)
  {
    _id: "178",
    rowType: "header",
    componentName: "Module 03 Life Limited Parts",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 179 - Centrifugal Impeller
  {
    _id: "179",
    rowType: "part",
    componentName: "Centrifugal Impeller PN:0292260110 SN:1546FRF",
    hourLimit1: "22000",
    hourLimit2: "C",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 180 - Injection Wheel
  {
    _id: "180",
    rowType: "part",
    componentName: "Injection Wheel PN:2292260750 SN:DD884CTF",
    hourLimit1: "8000",
    hourLimit2: "C",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 181 - HP Turbine Disc
  {
    _id: "181",
    rowType: "part",
    componentName: "HP Turbine Disc PN:2292260060 SN:CG043CTF",
    hourLimit1: "17000",
    hourLimit2: "C",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 182 - Usage Limited Parts (Header)
  {
    _id: "182",
    rowType: "header",
    componentName: "Usage Limited Parts",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 183 - HP Turbine Blades
  {
    _id: "183",
    rowType: "part",
    componentName: "HP Turbine Blades PN:229226A560 SN:38046",
    hourLimit1: "10000",
    hourLimit2: "C",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 184 - Module 04 (Header)
  {
    _id: "184",
    rowType: "header",
    componentName: "Module 04",
    hourLimit1: "4000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 185 - Life Limited Parts (Header)
  {
    _id: "185",
    rowType: "header",
    componentName: "Life Limited Parts",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 186 - Power Turbine Disc
  {
    _id: "186",
    rowType: "part",
    componentName: "Power Turbine Disc PN:2292810790 SN:CD817CTF",
    hourLimit1: "22000",
    hourLimit2: "C",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 187 - Power turbine blades
  {
    _id: "187",
    rowType: "part",
    componentName: "Power turbine blades PN:229281A440 SN:97024",
    hourLimit1: "10000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 188 - Power turbine nut
  {
    _id: "188",
    rowType: "part",
    componentName: "Power turbine nut PN:0292810450 SN:4273",
    hourLimit1: "6000",
    hourLimit2: "C",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 189 - Module 05 (Header)
  {
    _id: "189",
    rowType: "header",
    componentName: "Module 05",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 190 - Life Limited Parts (Header)
  {
    _id: "190",
    rowType: "header",
    componentName: "Life Limited Parts",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 191 - Sleeve Assy
  {
    _id: "191",
    rowType: "part",
    componentName: "Sleeve Assy PN:0292717600 SN:2562DMP",
    hourLimit1: "6000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "5475",
    dayType: "D",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 192 - Spline Nut
  {
    _id: "192",
    rowType: "part",
    componentName: "Spline Nut PN:0292710510 SN:1481",
    hourLimit1: "6000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "5475",
    dayType: "D",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 193 - Equipt Free Wheel Assy
  {
    _id: "193",
    rowType: "part",
    componentName: "Equipt Free Wheel Assy. PN:0292900200 SN:8596",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 194 - Free Wheel
  {
    _id: "194",
    rowType: "part",
    componentName: "Free Wheel PN:9560901230 SN:1687",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 195 - Bearing 1751SN
  {
    _id: "195",
    rowType: "part",
    componentName: "Bearing PN:9606651001 SN:1751SN",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 196 - Bearing 1756SN
  {
    _id: "196",
    rowType: "part",
    componentName: "Bearing PN:9606681001 SN:1756SN",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 197 - Bearing 1885SN
  {
    _id: "197",
    rowType: "part",
    componentName: "Bearing PN:9606490606 SN:1885SN",
    hourLimit1: "5000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 198 - Free Wheel Flange
  {
    _id: "198",
    rowType: "part",
    componentName: "Free Wheel Flange PN:0292900250 SN:1987CZ",
    hourLimit1: "90000",
    hourLimit2: "C",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 199 - Free Wheel Shaft
  {
    _id: "199",
    rowType: "part",
    componentName: "Free Wheel Shaft PN:0292900230 SN:5585",
    hourLimit1: "120000",
    hourLimit2: "C",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 200 - Pump& Metering Valve 51709
  {
    _id: "200",
    rowType: "part",
    componentName: "Pump& Metering Valve Assy,Adjusted PN:0292862200 SN:51709",
    hourLimit1: "4000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "3650",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 201 - Pump& Metering Valve 51688
  {
    _id: "201",
    rowType: "part",
    componentName: "Pump& Metering Valve Assy,Adjusted PN:0292862200 SN:51688",
    hourLimit1: "4000",
    hourLimit2: "H",
    hourLimit3: "",
    dayLimit: "3650",
    dayType: "",
    dateCW: "2020-06-10",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 202 - Valve Assy
  {
    _id: "202",
    rowType: "part",
    componentName: "Valve Assy PN:0292950800 SN:5239",
    hourLimit1: "",
    hourLimit2: "OC",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 203 - CARGO SLING INSPECTION (Header)
  {
    _id: "203",
    rowType: "header",
    componentName: "CARGO SLING INSPECTION",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },
  // Row 204 - EQUIPMENTS/ACCESSORIES (Header)
  {
    _id: "204",
    rowType: "header",
    componentName: "EQUIPMENTS/ACCESSORIES",
    hourLimit1: "",
    hourLimit2: "",
    hourLimit3: "",
    dayLimit: "",
    dayType: "",
    dateCW: "",
    hoursCW: "0",
    daysRemaining: "",
    timeRemaining: "",
    dateDue: "",
    ttCycleDue: "",
    due: "",
    hd: "",
    timeSinceInstall: "",
    totalTimeSinceNew: "",
  },

  ...Array.from({ length: 29 }, (_, i) => {
    const equipmentNames = [
      "EECU PN: 70BMN01060 SN:5623",
      "H. E. Igniter PN:9550168770 SN:19124746",
      "H. E. Igniter PN:9550168770 SN:20014247",
      "Alternator PN:9421003500 SN:2030",
      "H.E Box PN: 9421003400 SN:7680",
      "Electric magnetic plug PN:9550171750 SN:DV8376",
      "Magnetic Plug PN:9560171170 SN:28856",
      "Magnetic Plug PN:9560171170 SN:28857",
      "Speed Sensor PN:9550175810 SN:25342MXM",
      "Speed Sensor PN:9550175810 SN:25336MXM",
      "N2 Speed Sensor PN:9550175800 SN:25129MXM",
      "N2 Speed Sensor PN:9550175800 SN:25138MXM",
      "N2 Speed Sensor PN:9550175800 SN:25089MXM",
      "Equipped Valve Assy  PN:0292727300 SN:10531",
      "Engine data recorder PN:9580119130 SN:3914",
      "Control & Monitoring Harness PN:0292697770 SN:1694EL",
      "Control Harness PN:0292697830 SN:2149EL",
      "Harness,Pyrometric PN:9550178220 SN:12322",
      "Harness,Pyrometric PN:9550178230 SN:11659",
      "Fuel filter visual block indicator PN:9560166910 SN:A01936",
      "Injector PN:0283317500 SN: 22060C",
      "Injector PN:0283317500 SN: 22073C",
      "Oil Pump PN:0292125140 SN:4211MTL",
      "P3,PRES, Transmitter PN:9550171420 SN:BAY9704",
      "Exhaust pipe PN:0292810470 SN:1819EX",
      "Pressure transmitter PN:9421000800 SN:TMAD009794",
      "Pressure transmitter PN:9421000800 SN:TMAD009755",
      "Pressure and TemperatureTransmitter PN:9421001000 SN:TMAE008928",
      "Pressure and TemperatureTransmitter PN:9421001000 SN:TMAE009018",
      "Bleed valve PN:9550178980 SN:3279",
    ];
    return {
      _id: String(188 + i),
      rowType: "part",
      componentName: equipmentNames[i],
      hourLimit1: "",
      hourLimit2: "OC",
      hourLimit3: "",
      dayLimit: "",
      dayType: "",
      dateCW: "",
      hoursCW: "0",
      daysRemaining: "",
      timeRemaining: "",
      dateDue: "",
      ttCycleDue: "",
      due: "",
      hd: "",
      timeSinceInstall: "",
      totalTimeSinceNew: "",
    };
  }),
];
